// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

/**
 * Retrieve the Kubernetes version resource that describes the available Kubernetes versions for deployment.
 *
 * Uses Azure REST API version 2026-01-01-preview.
 */
export function getKubernetesVersion(args: GetKubernetesVersionArgs, opts?: pulumi.InvokeOptions): Promise<GetKubernetesVersionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("azure-native:networkcloud:getKubernetesVersion", {
        "kubernetesVersionName": args.kubernetesVersionName,
        "resourceGroupName": args.resourceGroupName,
    }, opts);
}

export interface GetKubernetesVersionArgs {
    /**
     * The name of the Kubernetes version resource.
     */
    kubernetesVersionName?: string;
    /**
     * The name of the resource group. The name is case insensitive.
     */
    resourceGroupName: string;
}

export interface GetKubernetesVersionResult {
    /**
     * The Azure API version of the resource.
     */
    readonly azureApiVersion: string;
    /**
     * Resource ETag.
     */
    readonly etag: string;
    /**
     * The extended location of the cluster associated with the resource.
     */
    readonly extendedLocation: outputs.networkcloud.ExtendedLocationResponse;
    /**
     * Fully qualified resource ID for the resource. E.g. "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
     */
    readonly id: string;
    /**
     * The geo-location where the resource lives
     */
    readonly location: string;
    /**
     * The name of the resource
     */
    readonly name: string;
    /**
     * The provisioning state of the Kubernetes version resource.
     */
    readonly provisioningState: string;
    /**
     * Azure Resource Manager metadata containing createdBy and modifiedBy information.
     */
    readonly systemData: outputs.networkcloud.SystemDataResponse;
    /**
     * Resource tags.
     */
    readonly tags?: {[key: string]: string};
    /**
     * The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
     */
    readonly type: string;
    /**
     * The list of available Kubernetes versions.
     */
    readonly values: outputs.networkcloud.KubernetesVersionValueResponse[];
}
/**
 * Retrieve the Kubernetes version resource that describes the available Kubernetes versions for deployment.
 *
 * Uses Azure REST API version 2026-01-01-preview.
 */
export function getKubernetesVersionOutput(args: GetKubernetesVersionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetKubernetesVersionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("azure-native:networkcloud:getKubernetesVersion", {
        "kubernetesVersionName": args.kubernetesVersionName,
        "resourceGroupName": args.resourceGroupName,
    }, opts);
}

export interface GetKubernetesVersionOutputArgs {
    /**
     * The name of the Kubernetes version resource.
     */
    kubernetesVersionName?: pulumi.Input<string | undefined>;
    /**
     * The name of the resource group. The name is case insensitive.
     */
    resourceGroupName: pulumi.Input<string>;
}
