// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../../types";
import * as utilities from "../../utilities";

/**
 * Response to get user settings
 */
export function getUserSettings(args: GetUserSettingsArgs, opts?: pulumi.InvokeOptions): Promise<GetUserSettingsResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("azure-native:portal/v20181001:getUserSettings", {
        "userSettingsName": args.userSettingsName,
    }, opts);
}

export interface GetUserSettingsArgs {
    /**
     * The name of the user settings
     */
    userSettingsName: string;
}

/**
 * Response to get user settings
 */
export interface GetUserSettingsResult {
    /**
     * The cloud shell user settings properties.
     */
    readonly properties: outputs.portal.v20181001.UserPropertiesResponse;
}

export function getUserSettingsOutput(args: GetUserSettingsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetUserSettingsResult> {
    return pulumi.output(args).apply(a => getUserSettings(a, opts))
}

export interface GetUserSettingsOutputArgs {
    /**
     * The name of the user settings
     */
    userSettingsName: pulumi.Input<string>;
}
