// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureNative.DataFactory.Outputs
{

    /// <summary>
    /// Databricks SparkPython activity properties.
    /// </summary>
    [OutputType]
    public sealed class DatabricksSparkPythonActivityTypePropertiesResponse
    {
        /// <summary>
        /// A list of libraries to be installed on the cluster that will execute the job.
        /// </summary>
        public readonly ImmutableArray<ImmutableDictionary<string, object>> Libraries;
        /// <summary>
        /// Command line parameters that will be passed to the Python file.
        /// </summary>
        public readonly ImmutableArray<object> Parameters;
        /// <summary>
        /// The URI of the Python file to be executed. DBFS paths are supported. Type: string (or Expression with resultType string).
        /// </summary>
        public readonly object PythonFile;

        [OutputConstructor]
        private DatabricksSparkPythonActivityTypePropertiesResponse(
            ImmutableArray<ImmutableDictionary<string, object>> libraries,

            ImmutableArray<object> parameters,

            object pythonFile)
        {
            Libraries = libraries;
            Parameters = parameters;
            PythonFile = pythonFile;
        }
    }
}
