// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureRM.EventGrid.Inputs
{

    /// <summary>
    /// Properties of the Domain.
    /// </summary>
    public sealed class DomainPropertiesResponseArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Endpoint for the domain.
        /// </summary>
        [Input("endpoint", required: true)]
        public Input<string> Endpoint { get; set; } = null!;

        [Input("inboundIpRules")]
        private InputList<Inputs.InboundIpRuleResponseArgs>? _inboundIpRules;

        /// <summary>
        /// This can be used to restrict traffic from specific IPs instead of all IPs. Note: These are considered only if PublicNetworkAccess is enabled.
        /// </summary>
        public InputList<Inputs.InboundIpRuleResponseArgs> InboundIpRules
        {
            get => _inboundIpRules ?? (_inboundIpRules = new InputList<Inputs.InboundIpRuleResponseArgs>());
            set => _inboundIpRules = value;
        }

        /// <summary>
        /// This determines the format that Event Grid should expect for incoming events published to the domain.
        /// </summary>
        [Input("inputSchema")]
        public Input<string>? InputSchema { get; set; }

        /// <summary>
        /// Information about the InputSchemaMapping which specified the info about mapping event payload.
        /// </summary>
        [Input("inputSchemaMapping")]
        public Input<Inputs.InputSchemaMappingResponseArgs>? InputSchemaMapping { get; set; }

        /// <summary>
        /// Metric resource id for the domain.
        /// </summary>
        [Input("metricResourceId", required: true)]
        public Input<string> MetricResourceId { get; set; } = null!;

        [Input("privateEndpointConnections")]
        private InputList<Inputs.PrivateEndpointConnectionResponseArgs>? _privateEndpointConnections;

        /// <summary>
        /// List of private endpoint connections.
        /// </summary>
        public InputList<Inputs.PrivateEndpointConnectionResponseArgs> PrivateEndpointConnections
        {
            get => _privateEndpointConnections ?? (_privateEndpointConnections = new InputList<Inputs.PrivateEndpointConnectionResponseArgs>());
            set => _privateEndpointConnections = value;
        }

        /// <summary>
        /// Provisioning state of the domain.
        /// </summary>
        [Input("provisioningState", required: true)]
        public Input<string> ProvisioningState { get; set; } = null!;

        /// <summary>
        /// This determines if traffic is allowed over public network. By default it is enabled. 
        /// You can further restrict to specific IPs by configuring &lt;seealso cref="P:Microsoft.Azure.Events.ResourceProvider.Common.Contracts.DomainProperties.InboundIpRules" /&gt;
        /// </summary>
        [Input("publicNetworkAccess")]
        public Input<string>? PublicNetworkAccess { get; set; }

        public DomainPropertiesResponseArgs()
        {
        }
    }
}
