// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureNative.DeviceRegistry.Outputs
{

    /// <summary>
    /// Connection endpoint URL a device can use to connect to a service.
    /// </summary>
    [OutputType]
    public sealed class DiscoveredMessagingEndpointsResponse
    {
        /// <summary>
        /// Set of endpoints to connect to the device.
        /// </summary>
        public readonly ImmutableDictionary<string, Outputs.DiscoveredInboundEndpointsResponse>? Inbound;
        /// <summary>
        /// Set of endpoints a device can connect to.
        /// </summary>
        public readonly Outputs.DiscoveredOutboundEndpointsResponse? Outbound;

        [OutputConstructor]
        private DiscoveredMessagingEndpointsResponse(
            ImmutableDictionary<string, Outputs.DiscoveredInboundEndpointsResponse>? inbound,

            Outputs.DiscoveredOutboundEndpointsResponse? outbound)
        {
            Inbound = inbound;
            Outbound = outbound;
        }
    }
}
