// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azurenative.servicefabricmesh.outputs;

import com.pulumi.azurenative.servicefabricmesh.outputs.ResourceLimitsResponse;
import com.pulumi.azurenative.servicefabricmesh.outputs.ResourceRequestsResponse;
import com.pulumi.core.annotations.CustomType;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ResourceRequirementsResponse {
    /**
     * @return Describes the maximum limits on the resources for a given container.
     * 
     */
    private @Nullable ResourceLimitsResponse limits;
    /**
     * @return Describes the requested resources for a given container.
     * 
     */
    private ResourceRequestsResponse requests;

    private ResourceRequirementsResponse() {}
    /**
     * @return Describes the maximum limits on the resources for a given container.
     * 
     */
    public Optional<ResourceLimitsResponse> limits() {
        return Optional.ofNullable(this.limits);
    }
    /**
     * @return Describes the requested resources for a given container.
     * 
     */
    public ResourceRequestsResponse requests() {
        return this.requests;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ResourceRequirementsResponse defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable ResourceLimitsResponse limits;
        private ResourceRequestsResponse requests;
        public Builder() {}
        public Builder(ResourceRequirementsResponse defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.limits = defaults.limits;
    	      this.requests = defaults.requests;
        }

        @CustomType.Setter
        public Builder limits(@Nullable ResourceLimitsResponse limits) {
            this.limits = limits;
            return this;
        }
        @CustomType.Setter
        public Builder requests(ResourceRequestsResponse requests) {
            this.requests = Objects.requireNonNull(requests);
            return this;
        }
        public ResourceRequirementsResponse build() {
            final var o = new ResourceRequirementsResponse();
            o.limits = limits;
            o.requests = requests;
            return o;
        }
    }
}
