// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureNextGen.Cdn.V20200415.Inputs
{

    /// <summary>
    /// The origin group for CDN content which is added when creating a CDN endpoint. Traffic is sent to the origins within the origin group based on origin health.
    /// </summary>
    public sealed class DeepCreatedOriginGroupArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Health probe settings to the origin that is used to determine the health of the origin.
        /// </summary>
        [Input("healthProbeSettings")]
        public Input<Inputs.HealthProbeParametersArgs>? HealthProbeSettings { get; set; }

        /// <summary>
        /// Origin group name which must be unique within the endpoint.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("origins", required: true)]
        private InputList<Inputs.ResourceReferenceArgs>? _origins;

        /// <summary>
        /// The source of the content being delivered via CDN within given origin group.
        /// </summary>
        public InputList<Inputs.ResourceReferenceArgs> Origins
        {
            get => _origins ?? (_origins = new InputList<Inputs.ResourceReferenceArgs>());
            set => _origins = value;
        }

        /// <summary>
        /// The JSON object that contains the properties to determine origin health using real requests/responses.This property is currently not supported.
        /// </summary>
        [Input("responseBasedOriginErrorDetectionSettings")]
        public Input<Inputs.ResponseBasedOriginErrorDetectionParametersArgs>? ResponseBasedOriginErrorDetectionSettings { get; set; }

        /// <summary>
        /// Time in minutes to shift the traffic to the endpoint gradually when an unhealthy endpoint comes healthy or a new endpoint is added. Default is 10 mins. This property is currently not supported.
        /// </summary>
        [Input("trafficRestorationTimeToHealedOrNewEndpointsInMinutes")]
        public Input<int>? TrafficRestorationTimeToHealedOrNewEndpointsInMinutes { get; set; }

        public DeepCreatedOriginGroupArgs()
        {
        }
    }
}
