before:
  hooks:
  - make init_submodules
  - make codegen
  - make generate_schema
builds:
- dir: provider
  env:
  - GO111MODULE=on
  goos:
  - darwin
  - windows
  - linux
  goarch:
  - amd64
  - arm64
  ignore: []
  main: ./cmd/pulumi-resource-azure-native/
  ldflags:
  - -X
    github.com/pulumi/pulumi-azure-native/provider/pkg/version.Version={{.Tag}}
  binary: pulumi-resource-azure-native
archives:
- name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  id: archive
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  skip: true
release:
  disable: false
blobs:
- provider: s3
  region: us-west-2
  bucket: get.pulumi.com
  folder: releases/plugins/
  ids:
  - archive
