before:
  hooks:
    - make arm2pulumi_prebuild
builds:
  - goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    ldflags: -X github.com/pulumi/pulumi-aws-native/provider/version.Version={{.Tag}}
    binary: arm2pulumi
    dir: provider
    main: ./cmd/arm2pulumi/
archives:
  - name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x64
      386: x86
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  skip: true
release:
  name_template: "v{{.Version}}"
project_name: arm2pulumi
brews:
  -
    name: arm2pulumi
    tap:
      owner: pulumi
      name: homebrew-tap
    commit_author:
      name: pulumi-bot
      email: bot@pulumi.com
    homepage: "https://pulumi.com"
    description: "A tool to convert Azure ARM Templates to Pulumi programs"
    folder: Formula
    license: Apache-2.0
