// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azurenative.compute.inputs;

import com.pulumi.azurenative.compute.inputs.CloudServiceExtensionPropertiesArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * Describes a cloud service Extension.
 * 
 */
public final class ExtensionArgs extends com.pulumi.resources.ResourceArgs {

    public static final ExtensionArgs Empty = new ExtensionArgs();

    /**
     * The name of the extension.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the extension.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Extension Properties.
     * 
     */
    @Import(name="properties")
    private @Nullable Output<CloudServiceExtensionPropertiesArgs> properties;

    /**
     * @return Extension Properties.
     * 
     */
    public Optional<Output<CloudServiceExtensionPropertiesArgs>> properties() {
        return Optional.ofNullable(this.properties);
    }

    private ExtensionArgs() {}

    private ExtensionArgs(ExtensionArgs $) {
        this.name = $.name;
        this.properties = $.properties;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ExtensionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ExtensionArgs $;

        public Builder() {
            $ = new ExtensionArgs();
        }

        public Builder(ExtensionArgs defaults) {
            $ = new ExtensionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the extension.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the extension.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param properties Extension Properties.
         * 
         * @return builder
         * 
         */
        public Builder properties(@Nullable Output<CloudServiceExtensionPropertiesArgs> properties) {
            $.properties = properties;
            return this;
        }

        /**
         * @param properties Extension Properties.
         * 
         * @return builder
         * 
         */
        public Builder properties(CloudServiceExtensionPropertiesArgs properties) {
            return properties(Output.of(properties));
        }

        public ExtensionArgs build() {
            return $;
        }
    }

}
