// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v20200101

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Represents MCAS (Microsoft Cloud App Security) data connector.
func LookupMCASDataConnector(ctx *pulumi.Context, args *LookupMCASDataConnectorArgs, opts ...pulumi.InvokeOption) (*LookupMCASDataConnectorResult, error) {
	var rv LookupMCASDataConnectorResult
	err := ctx.Invoke("azure-native:securityinsights/v20200101:getMCASDataConnector", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupMCASDataConnectorArgs struct {
	// Connector ID
	DataConnectorId string `pulumi:"dataConnectorId"`
	// The name of the resource group within the user's subscription. The name is case insensitive.
	ResourceGroupName string `pulumi:"resourceGroupName"`
	// The name of the workspace.
	WorkspaceName string `pulumi:"workspaceName"`
}

// Represents MCAS (Microsoft Cloud App Security) data connector.
type LookupMCASDataConnectorResult struct {
	// The available data types for the connector.
	DataTypes *MCASDataConnectorDataTypesResponse `pulumi:"dataTypes"`
	// Etag of the azure resource
	Etag *string `pulumi:"etag"`
	// Azure resource Id
	Id string `pulumi:"id"`
	// The kind of the data connector
	// Expected value is 'MicrosoftCloudAppSecurity'.
	Kind string `pulumi:"kind"`
	// Azure resource name
	Name string `pulumi:"name"`
	// The tenant id to connect to, and get the data from.
	TenantId *string `pulumi:"tenantId"`
	// Azure resource type
	Type string `pulumi:"type"`
}

func LookupMCASDataConnectorOutput(ctx *pulumi.Context, args LookupMCASDataConnectorOutputArgs, opts ...pulumi.InvokeOption) LookupMCASDataConnectorResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupMCASDataConnectorResult, error) {
			args := v.(LookupMCASDataConnectorArgs)
			r, err := LookupMCASDataConnector(ctx, &args, opts...)
			var s LookupMCASDataConnectorResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupMCASDataConnectorResultOutput)
}

type LookupMCASDataConnectorOutputArgs struct {
	// Connector ID
	DataConnectorId pulumi.StringInput `pulumi:"dataConnectorId"`
	// The name of the resource group within the user's subscription. The name is case insensitive.
	ResourceGroupName pulumi.StringInput `pulumi:"resourceGroupName"`
	// The name of the workspace.
	WorkspaceName pulumi.StringInput `pulumi:"workspaceName"`
}

func (LookupMCASDataConnectorOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMCASDataConnectorArgs)(nil)).Elem()
}

// Represents MCAS (Microsoft Cloud App Security) data connector.
type LookupMCASDataConnectorResultOutput struct{ *pulumi.OutputState }

func (LookupMCASDataConnectorResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMCASDataConnectorResult)(nil)).Elem()
}

func (o LookupMCASDataConnectorResultOutput) ToLookupMCASDataConnectorResultOutput() LookupMCASDataConnectorResultOutput {
	return o
}

func (o LookupMCASDataConnectorResultOutput) ToLookupMCASDataConnectorResultOutputWithContext(ctx context.Context) LookupMCASDataConnectorResultOutput {
	return o
}

// The available data types for the connector.
func (o LookupMCASDataConnectorResultOutput) DataTypes() MCASDataConnectorDataTypesResponsePtrOutput {
	return o.ApplyT(func(v LookupMCASDataConnectorResult) *MCASDataConnectorDataTypesResponse { return v.DataTypes }).(MCASDataConnectorDataTypesResponsePtrOutput)
}

// Etag of the azure resource
func (o LookupMCASDataConnectorResultOutput) Etag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMCASDataConnectorResult) *string { return v.Etag }).(pulumi.StringPtrOutput)
}

// Azure resource Id
func (o LookupMCASDataConnectorResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMCASDataConnectorResult) string { return v.Id }).(pulumi.StringOutput)
}

// The kind of the data connector
// Expected value is 'MicrosoftCloudAppSecurity'.
func (o LookupMCASDataConnectorResultOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMCASDataConnectorResult) string { return v.Kind }).(pulumi.StringOutput)
}

// Azure resource name
func (o LookupMCASDataConnectorResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMCASDataConnectorResult) string { return v.Name }).(pulumi.StringOutput)
}

// The tenant id to connect to, and get the data from.
func (o LookupMCASDataConnectorResultOutput) TenantId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMCASDataConnectorResult) *string { return v.TenantId }).(pulumi.StringPtrOutput)
}

// Azure resource type
func (o LookupMCASDataConnectorResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMCASDataConnectorResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupMCASDataConnectorResultOutput{})
}
