// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureNative.Network
{
    public static class GetNetworkInterfaceTapConfiguration
    {
        /// <summary>
        /// Get the specified tap configuration on a network interface.
        /// API Version: 2020-11-01.
        /// </summary>
        public static Task<GetNetworkInterfaceTapConfigurationResult> InvokeAsync(GetNetworkInterfaceTapConfigurationArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetNetworkInterfaceTapConfigurationResult>("azure-native:network:getNetworkInterfaceTapConfiguration", args ?? new GetNetworkInterfaceTapConfigurationArgs(), options.WithDefaults());

        /// <summary>
        /// Get the specified tap configuration on a network interface.
        /// API Version: 2020-11-01.
        /// </summary>
        public static Output<GetNetworkInterfaceTapConfigurationResult> Invoke(GetNetworkInterfaceTapConfigurationInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetNetworkInterfaceTapConfigurationResult>("azure-native:network:getNetworkInterfaceTapConfiguration", args ?? new GetNetworkInterfaceTapConfigurationInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNetworkInterfaceTapConfigurationArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the network interface.
        /// </summary>
        [Input("networkInterfaceName", required: true)]
        public string NetworkInterfaceName { get; set; } = null!;

        /// <summary>
        /// The name of the resource group.
        /// </summary>
        [Input("resourceGroupName", required: true)]
        public string ResourceGroupName { get; set; } = null!;

        /// <summary>
        /// The name of the tap configuration.
        /// </summary>
        [Input("tapConfigurationName", required: true)]
        public string TapConfigurationName { get; set; } = null!;

        public GetNetworkInterfaceTapConfigurationArgs()
        {
        }
        public static new GetNetworkInterfaceTapConfigurationArgs Empty => new GetNetworkInterfaceTapConfigurationArgs();
    }

    public sealed class GetNetworkInterfaceTapConfigurationInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the network interface.
        /// </summary>
        [Input("networkInterfaceName", required: true)]
        public Input<string> NetworkInterfaceName { get; set; } = null!;

        /// <summary>
        /// The name of the resource group.
        /// </summary>
        [Input("resourceGroupName", required: true)]
        public Input<string> ResourceGroupName { get; set; } = null!;

        /// <summary>
        /// The name of the tap configuration.
        /// </summary>
        [Input("tapConfigurationName", required: true)]
        public Input<string> TapConfigurationName { get; set; } = null!;

        public GetNetworkInterfaceTapConfigurationInvokeArgs()
        {
        }
        public static new GetNetworkInterfaceTapConfigurationInvokeArgs Empty => new GetNetworkInterfaceTapConfigurationInvokeArgs();
    }


    [OutputType]
    public sealed class GetNetworkInterfaceTapConfigurationResult
    {
        /// <summary>
        /// A unique read-only string that changes whenever the resource is updated.
        /// </summary>
        public readonly string Etag;
        /// <summary>
        /// Resource ID.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The name of the resource that is unique within a resource group. This name can be used to access the resource.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// The provisioning state of the network interface tap configuration resource.
        /// </summary>
        public readonly string ProvisioningState;
        /// <summary>
        /// Sub Resource type.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// The reference to the Virtual Network Tap resource.
        /// </summary>
        public readonly Outputs.VirtualNetworkTapResponse? VirtualNetworkTap;

        [OutputConstructor]
        private GetNetworkInterfaceTapConfigurationResult(
            string etag,

            string? id,

            string? name,

            string provisioningState,

            string type,

            Outputs.VirtualNetworkTapResponse? virtualNetworkTap)
        {
            Etag = etag;
            Id = id;
            Name = name;
            ProvisioningState = provisioningState;
            Type = type;
            VirtualNetworkTap = virtualNetworkTap;
        }
    }
}
