// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureNative.App.V20220301.Inputs
{

    /// <summary>
    /// Non versioned Container App configuration properties that define the mutable settings of a Container app
    /// </summary>
    public sealed class ConfigurationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ActiveRevisionsMode controls how active revisions are handled for the Container app:
        /// &lt;list&gt;&lt;item&gt;Multiple: multiple revisions can be active.&lt;/item&gt;&lt;item&gt;Single: Only one revision can be active at a time. Revision weights can not be used in this mode. If no value if provided, this is the default.&lt;/item&gt;&lt;/list&gt;
        /// </summary>
        [Input("activeRevisionsMode")]
        public InputUnion<string, Pulumi.AzureNative.App.V20220301.ActiveRevisionsMode>? ActiveRevisionsMode { get; set; }

        /// <summary>
        /// Dapr configuration for the Container App.
        /// </summary>
        [Input("dapr")]
        public Input<Inputs.DaprArgs>? Dapr { get; set; }

        /// <summary>
        /// Ingress configurations.
        /// </summary>
        [Input("ingress")]
        public Input<Inputs.IngressArgs>? Ingress { get; set; }

        [Input("registries")]
        private InputList<Inputs.RegistryCredentialsArgs>? _registries;

        /// <summary>
        /// Collection of private container registry credentials for containers used by the Container app
        /// </summary>
        public InputList<Inputs.RegistryCredentialsArgs> Registries
        {
            get => _registries ?? (_registries = new InputList<Inputs.RegistryCredentialsArgs>());
            set => _registries = value;
        }

        [Input("secrets")]
        private InputList<Inputs.SecretArgs>? _secrets;

        /// <summary>
        /// Collection of secrets used by a Container app
        /// </summary>
        public InputList<Inputs.SecretArgs> Secrets
        {
            get => _secrets ?? (_secrets = new InputList<Inputs.SecretArgs>());
            set => _secrets = value;
        }

        public ConfigurationArgs()
        {
        }
        public static new ConfigurationArgs Empty => new ConfigurationArgs();
    }
}
