ADHybridHealthService: {}
AVS:
    tracking: "2022-05-01"
Aad:
    tracking: "2022-12-01"
AadIam:
    tracking: "2020-03-01"
    additions:
        DiagnosticSetting: "2017-04-01"
Addons:
    tracking: "2018-03-01"
Advisor:
    tracking: "2022-09-01"
AgFoodPlatform:
    tracking: 2021-09-01-preview
AlertsManagement:
    tracking: "2021-08-08"
    additions:
        SmartDetectorAlertRule: "2021-04-01"
AnalysisServices:
    tracking: "2017-08-01"
ApiManagement:
    tracking: "2021-08-01"
    additions:
        ApiDiagnosticLogger: "2018-01-01"
        ApiOperationsPolicy: "2016-10-10"
        DiagnosticLogger: "2018-01-01"
        Property: "2019-01-01"
        TagDescription: "2018-01-01"
        TenantPolicy: "2016-10-10"
        listTenantAccessGitSecrets: "2019-12-01"
App:
    tracking: "2022-10-01"
AppComplianceAutomation:
    tracking: 2022-11-16-preview
AppConfiguration:
    tracking: "2022-05-01"
    additions:
        listConfigurationStoreKeyValue: "2020-06-01"
AppPlatform:
    tracking: "2022-12-01"
Attestation:
    tracking: "2020-10-01"
Authorization:
    tracking: "2022-06-01"
    additions:
        ManagementLockAtResourceGroupLevel: "2020-05-01"
        ManagementLockAtResourceLevel: "2020-05-01"
        ManagementLockAtSubscriptionLevel: "2020-05-01"
        ManagementLockByScope: "2020-05-01"
        PolicyDefinition: "2021-06-01"
        PolicyDefinitionAtManagementGroup: "2021-06-01"
        PolicySetDefinition: "2021-06-01"
        PolicySetDefinitionAtManagementGroup: "2021-06-01"
        PrivateLinkAssociation: "2020-05-01"
        ResourceManagementPrivateLink: "2020-05-01"
        RoleAssignment: "2022-04-01"
        RoleDefinition: "2022-04-01"
        RoleManagementPolicyAssignment: "2020-10-01"
Automanage:
    tracking: "2022-05-04"
Automation:
    tracking: "2022-08-08"
    additions:
        SoftwareUpdateConfigurationByName: "2019-06-01"
        Watcher: "2019-06-01"
        Webhook: "2015-10-31"
AutonomousDevelopmentPlatform:
    tracking: 2021-11-01-preview
AzureActiveDirectory:
    tracking: "2021-04-01"
AzureArcData:
    tracking: "2021-11-01"
AzureData:
    tracking: 2019-07-24-preview
AzureStack:
    tracking: "2022-06-01"
AzureStackHCI:
    tracking: "2022-12-01"
BareMetalInfrastructure: {}
Batch:
    tracking: "2022-10-01"
    additions:
        Certificate: "2022-06-01"
Billing:
    tracking: "2020-05-01"
BillingBenefits: {}
Blockchain:
    tracking: 2018-06-01-preview
Blueprint:
    tracking: 2018-11-01-preview
BotService:
    tracking: 2022-06-15-preview
    additions:
        EnterpriseChannel: "2018-07-12"
Cache:
    tracking: "2022-06-01"
    additions:
        Database: "2022-01-01"
        RedisEnterprise: "2022-01-01"
        listDatabaseKeys: "2022-01-01"
Capacity: {}
Cdn:
    tracking: 2022-11-01-preview
CertificateRegistration:
    tracking: "2022-03-01"
ChangeAnalysis:
    tracking: 2020-04-01-preview
Chaos:
    tracking: 2022-10-01-preview
CognitiveServices:
    tracking: "2022-10-01"
Commerce: {}
Communication:
    tracking: 2022-07-01-preview
Compute:
    tracking: "2022-09-04"
    additions:
        AvailabilitySet: "2022-08-01"
        CapacityReservation: "2022-08-01"
        CapacityReservationGroup: "2022-08-01"
        DedicatedHost: "2022-08-01"
        DedicatedHostGroup: "2022-08-01"
        Disk: "2022-07-02"
        DiskAccess: "2022-07-02"
        DiskAccessAPrivateEndpointConnection: "2022-07-02"
        DiskEncryptionSet: "2022-07-02"
        Gallery: "2022-03-03"
        GalleryApplication: "2022-03-03"
        GalleryApplicationVersion: "2022-03-03"
        GalleryImage: "2022-03-03"
        GalleryImageVersion: "2022-03-03"
        Image: "2022-08-01"
        ProximityPlacementGroup: "2022-08-01"
        RestorePoint: "2022-08-01"
        RestorePointCollection: "2022-08-01"
        Snapshot: "2022-07-02"
        SshPublicKey: "2022-08-01"
        VirtualMachine: "2022-08-01"
        VirtualMachineExtension: "2022-08-01"
        VirtualMachineRunCommandByVirtualMachine: "2022-08-01"
        VirtualMachineScaleSet: "2022-08-01"
        VirtualMachineScaleSetExtension: "2022-08-01"
        VirtualMachineScaleSetVM: "2022-08-01"
        VirtualMachineScaleSetVMExtension: "2022-08-01"
        VirtualMachineScaleSetVMRunCommand: "2022-08-01"
        getLogAnalyticExportRequestRateByInterval: "2022-08-01"
        getLogAnalyticExportThrottledRequests: "2022-08-01"
ConfidentialLedger:
    tracking: "2022-05-13"
Confluent:
    tracking: "2021-12-01"
ConnectedVMwarevSphere:
    tracking: 2022-07-15-preview
Consumption:
    tracking: "2021-10-01"
ContainerInstance:
    tracking: "2022-09-01"
ContainerRegistry:
    tracking: "2021-09-01"
    additions:
        Task: "2019-04-01"
        listRegistryBuildSourceUploadUrl: "2019-04-01"
        listRunLogSasUrl: "2019-04-01"
        listTaskDetails: "2019-04-01"
ContainerService:
    tracking: "2022-09-01"
    additions:
        OpenShiftManagedCluster: "2019-04-30"
        listManagedClusterAccessProfile: "2020-03-01"
CostManagement:
    tracking: "2022-10-01"
    additions:
        Setting: "2019-11-01"
CustomProviders:
    tracking: 2018-09-01-preview
CustomerInsights:
    tracking: "2017-04-26"
CustomerLockbox: {}
DBforMariaDB:
    tracking: "2018-06-01"
DBforMySQL:
    tracking: "2021-05-01"
    additions:
        Configuration: "2017-12-01"
        PrivateEndpointConnection: "2018-06-01"
        ServerAdministrator: "2017-12-01"
        ServerKey: "2020-01-01"
        VirtualNetworkRule: "2017-12-01"
DBforPostgreSQL:
    tracking: "2021-06-01"
    additions:
        PrivateEndpointConnection: "2018-06-01"
        ServerAdministrator: "2017-12-01"
        ServerKey: "2020-01-01"
        ServerSecurityAlertPolicy: "2017-12-01"
        VirtualNetworkRule: "2017-12-01"
Dashboard:
    tracking: "2022-08-01"
DataBox:
    tracking: "2022-09-01"
DataBoxEdge:
    tracking: "2022-03-01"
DataCatalog:
    tracking: "2016-03-30"
DataFactory:
    tracking: "2018-06-01"
DataLakeAnalytics:
    tracking: 2019-11-01-preview
DataLakeStore:
    tracking: "2016-11-01"
DataMigration:
    tracking: "2021-06-30"
DataProtection:
    tracking: "2022-05-01"
DataShare:
    tracking: "2021-08-01"
Databricks:
    tracking: 2022-04-01-preview
Datadog:
    tracking: "2022-06-01"
DelegatedNetwork:
    tracking: "2021-03-15"
DeploymentManager:
    tracking: 2019-11-01-preview
DesktopVirtualization:
    tracking: "2022-09-09"
DevCenter:
    tracking: 2022-11-11-preview
DevHub:
    tracking: 2022-04-01-preview
DevOps: {}
DevSpaces:
    tracking: "2019-04-01"
DevTestLab:
    tracking: "2018-09-15"
DeviceUpdate:
    tracking: "2022-10-01"
Devices:
    tracking: "2022-02-05"
    additions:
        Certificate: "2021-07-02"
        IotHubResource: "2021-07-02"
        IotHubResourceEventHubConsumerGroup: "2021-07-02"
        PrivateEndpointConnection: "2021-07-02"
        listIotHubResourceKeys: "2021-07-02"
        listIotHubResourceKeysForKeyName: "2021-07-02"
DigitalTwins:
    tracking: "2022-10-31"
DocumentDB:
    tracking: "2022-08-15"
DomainRegistration:
    tracking: "2022-03-01"
Dynamics365Fraudprotection:
    tracking: 2021-02-01-preview
DynamicsTelemetry: {}
Easm:
    tracking: 2022-04-01-preview
EdgeOrder:
    tracking: "2021-12-01"
EdgeOrderPartner: {}
Education:
    tracking: 2021-12-01-preview
Elastic:
    tracking: 2022-07-01-preview
ElasticSan:
    tracking: 2021-11-20-preview
EngagementFabric:
    tracking: 2018-09-01-preview
EnterpriseKnowledgeGraph:
    tracking: "2018-12-03"
EventGrid:
    tracking: "2022-06-15"
EventHub:
    tracking: "2021-11-01"
ExtendedLocation:
    tracking: "2021-08-15"
Features:
    tracking: "2021-07-01"
FluidRelay:
    tracking: "2022-06-01"
    additions:
        getFluidRelayServerKeys: "2022-05-26"
GuestConfiguration:
    tracking: "2022-01-25"
HDInsight:
    tracking: "2021-06-01"
HanaOnAzure:
    tracking: 2020-02-07-preview
    additions:
        HanaInstance: 2017-11-03-preview
HardwareSecurityModules:
    tracking: "2021-11-30"
HealthBot:
    tracking: "2022-08-08"
HealthcareApis:
    tracking: "2022-06-01"
HybridCompute:
    tracking: "2022-03-10"
HybridConnectivity:
    tracking: 2022-05-01-preview
HybridContainerService:
    tracking: 2022-05-01-preview
HybridData:
    tracking: "2019-06-01"
HybridNetwork:
    tracking: "2021-05-01"
ImportExport:
    tracking: "2021-01-01"
Insights:
    tracking: "2022-10-01"
    additions:
        ActionGroup: "2022-06-01"
        ActivityLogAlert: "2020-10-01"
        AlertRule: "2016-03-01"
        AnalyticsItem: "2015-05-01"
        Component: "2020-02-02"
        ComponentCurrentBillingFeature: "2015-05-01"
        DataCollectionEndpoint: "2021-04-01"
        DataCollectionRule: "2021-04-01"
        DataCollectionRuleAssociation: "2021-04-01"
        ExportConfiguration: "2015-05-01"
        Favorite: "2015-05-01"
        LogProfile: "2016-03-01"
        MetricAlert: "2018-03-01"
        MyWorkbook: "2021-03-08"
        ProactiveDetectionConfiguration: "2015-05-01"
        ScheduledQueryRule: "2022-06-15"
        WebTest: "2022-06-15"
        Workbook: "2022-04-01"
        WorkbookTemplate: "2020-11-20"
        getLiveToken: "2021-10-14"
        listEASubscriptionListMigrationDatePost: "2017-10-01"
Intune:
    tracking: 2015-01-14-preview
IoTCentral:
    tracking: "2021-06-01"
IoTSecurity:
    tracking: 2021-02-01-preview
KeyVault:
    tracking: "2022-07-01"
Kubernetes:
    tracking: "2021-10-01"
KubernetesConfiguration:
    tracking: "2022-11-01"
Kusto:
    tracking: "2022-07-07"
LabServices:
    tracking: "2022-08-01"
    additions:
        Environment: "2018-10-15"
        EnvironmentSetting: "2018-10-15"
        GalleryImage: "2018-10-15"
        LabAccount: "2018-10-15"
        getGlobalUserEnvironment: "2018-10-15"
        getGlobalUserOperationBatchStatus: "2018-10-15"
        getGlobalUserOperationStatus: "2018-10-15"
        getGlobalUserPersonalPreferences: "2018-10-15"
        getLabAccountRegionalAvailability: "2018-10-15"
        listGlobalUserEnvironments: "2018-10-15"
        listGlobalUserLabs: "2018-10-15"
LoadTestService:
    tracking: "2022-12-01"
Logic:
    tracking: "2019-05-01"
    additions:
        Agreement: "2016-06-01"
        Certificate: "2016-06-01"
        Map: "2016-06-01"
        Partner: "2016-06-01"
        RosettaNetProcessConfiguration: "2016-06-01"
        Schema: "2016-06-01"
        Session: "2016-06-01"
        listAgreementContentCallbackUrl: "2016-06-01"
        listMapContentCallbackUrl: "2016-06-01"
        listPartnerContentCallbackUrl: "2016-06-01"
        listSchemaContentCallbackUrl: "2016-06-01"
        listWorkflowVersionCallbackUrl: "2016-06-01"
Logz:
    tracking: 2022-01-01-preview
M365SecurityAndCompliance:
    tracking: 2021-03-25-preview
MachineLearning:
    tracking: "2019-10-01"
    additions:
        WebService: "2017-01-01"
MachineLearningCompute:
    tracking: 2017-08-01-preview
MachineLearningExperimentation:
    tracking: 2017-05-01-preview
MachineLearningServices:
    tracking: "2022-10-01"
    additions:
        LinkedWorkspace: "2020-03-01"
        MachineLearningCompute: "2021-04-01"
        MachineLearningService: "2021-04-01"
        listMachineLearningComputeKeys: "2021-04-01"
        listMachineLearningComputeNodes: "2021-04-01"
        listNotebookKeys: "2021-04-01"
        listStorageAccountKeys: "2021-04-01"
Maintenance:
    tracking: 2022-07-01-preview
ManagedIdentity:
    tracking: 2022-01-31-preview
ManagedNetwork:
    tracking: 2019-06-01-preview
ManagedServices:
    tracking: "2022-10-01"
Management:
    tracking: "2021-04-01"
ManagementPartner:
    tracking: "2018-02-01"
Maps:
    tracking: "2021-02-01"
Marketplace:
    tracking: "2022-09-01"
    additions:
        PrivateStoreOffer: "2020-01-01"
MarketplaceNotifications: {}
MarketplaceOrdering: {}
Media:
    tracking: "2022-08-01"
    additions:
        Job: "2021-11-01"
        MediaService: "2021-11-01"
        PrivateEndpointConnection: "2021-11-01"
        Transform: "2021-11-01"
        listMediaServiceEdgePolicies: "2021-11-01"
        listMediaServiceKeys: "2015-10-01"
Migrate:
    tracking: "2021-08-01"
    additions:
        Assessment: "2019-10-01"
        Group: "2019-10-01"
        HyperVCollector: "2019-10-01"
        ImportCollector: "2019-10-01"
        MigrateProjectsControllerMigrateProject: "2020-05-01"
        PrivateEndpointConnection: "2019-10-01"
        PrivateEndpointConnectionControllerPrivateEndpointConnection: "2020-05-01"
        Project: "2019-10-01"
        ServerCollector: "2019-10-01"
        VMwareCollector: "2019-10-01"
        getProjectKeys: "2018-02-02"
MixedReality:
    tracking: "2021-01-01"
MobileNetwork:
    tracking: "2022-11-01"
Monitor:
    tracking: 2021-06-03-preview
NetApp:
    tracking: "2022-05-01"
Network:
    tracking: "2022-07-01"
    additions:
        Endpoint: "2018-08-01"
        Experiment: "2019-11-01"
        FirewallPolicyRuleGroup: "2020-04-01"
        FrontDoor: "2021-06-01"
        InterfaceEndpoint: "2019-02-01"
        NetworkExperimentProfile: "2019-11-01"
        P2sVpnServerConfiguration: "2019-07-01"
        Policy: "2022-05-01"
        PrivateRecordSet: "2020-06-01"
        PrivateZone: "2020-06-01"
        Profile: "2018-08-01"
        RecordSet: "2018-05-01"
        RulesEngine: "2021-06-01"
        TrafficManagerUserMetricsKey: "2018-08-01"
        VirtualWAN: "2018-07-01"
        Zone: "2018-05-01"
        getDnsResourceReferenceByTarResources: "2018-05-01"
NetworkFunction:
    tracking: "2022-11-01"
NotificationHubs:
    tracking: "2017-04-01"
OffAzure:
    tracking: "2020-07-07"
OpenEnergyPlatform:
    tracking: 2022-04-04-preview
OperationalInsights:
    tracking: "2022-10-01"
    additions:
        Cluster: "2021-06-01"
        DataExport: "2020-08-01"
        DataSource: "2020-08-01"
        LinkedService: "2020-08-01"
        LinkedStorageAccount: "2020-08-01"
        Query: "2019-09-01"
        QueryPack: "2019-09-01"
        SavedSearch: "2020-08-01"
        StorageInsightConfig: "2020-08-01"
        getSharedKeys: "2020-08-01"
OperationsManagement:
    tracking: 2015-11-01-preview
Orbital:
    tracking: "2022-03-01"
Peering:
    tracking: "2022-10-01"
PolicyInsights:
    tracking: "2022-09-01"
    additions:
        RemediationAtManagementGroup: "2021-10-01"
        RemediationAtResource: "2021-10-01"
        RemediationAtResourceGroup: "2021-10-01"
        RemediationAtSubscription: "2021-10-01"
        listRemediationDeploymentsAtManagementGroup: "2021-10-01"
        listRemediationDeploymentsAtResource: "2021-10-01"
        listRemediationDeploymentsAtResourceGroup: "2021-10-01"
        listRemediationDeploymentsAtSubscription: "2021-10-01"
Portal:
    tracking: 2020-09-01-preview
    additions:
        Console: "2018-10-01"
        ConsoleWithLocation: "2018-10-01"
        UserSettings: "2018-10-01"
        UserSettingsWithLocation: "2018-10-01"
PowerBI:
    tracking: "2020-06-01"
    additions:
        WorkspaceCollection: "2016-01-29"
        listWorkspaceCollectionAccessKeys: "2016-01-29"
PowerBIDedicated:
    tracking: "2021-01-01"
PowerPlatform:
    tracking: 2020-10-30-preview
ProviderHub:
    tracking: "2020-11-20"
Purview:
    tracking: "2021-07-01"
Quantum:
    tracking: 2022-01-10-preview
Quota: {}
RecommendationsService:
    tracking: "2022-02-01"
RecoveryServices:
    tracking: "2022-10-01"
    additions:
        getRecoveryPointAccessToken: "2021-11-15"
RedHatOpenShift:
    tracking: "2022-09-04"
Relay:
    tracking: "2021-11-01"
ResourceConnector:
    tracking: "2022-10-27"
ResourceGraph:
    tracking: 2020-04-01-preview
ResourceHealth: {}
Resources:
    tracking: "2022-09-01"
    additions:
        DeploymentScript: "2020-10-01"
        TemplateSpec: "2022-02-01"
        TemplateSpecVersion: "2022-02-01"
SaaS:
    tracking: 2018-03-01-beta
ScVmm:
    tracking: 2020-06-05-preview
Scheduler:
    tracking: "2016-03-01"
Search:
    tracking: "2020-08-01"
Security:
    tracking: 2022-11-20-preview
    additions:
        AdaptiveApplicationControl: "2020-01-01"
        AdvancedThreatProtection: "2019-01-01"
        Application: 2022-07-01-preview
        Assessment: "2021-06-01"
        AssessmentMetadataInSubscription: "2021-06-01"
        DeviceSecurityGroup: "2019-08-01"
        IotSecuritySolution: "2019-08-01"
        JitNetworkAccessPolicy: "2020-01-01"
        SecurityConnector: 2022-08-01-preview
        SecurityConnectorApplication: 2022-07-01-preview
        ServerVulnerabilityAssessment: "2020-01-01"
SecurityAndCompliance:
    tracking: "2021-03-08"
SecurityDevOps:
    tracking: 2022-09-01-preview
SecurityInsights:
    tracking: "2022-11-01"
SerialConsole:
    tracking: "2018-05-01"
ServiceBus:
    tracking: "2021-11-01"
ServiceFabric:
    tracking: "2022-01-01"
    additions:
        Cluster: "2021-06-01"
        listClusterUpgradableVersions: "2021-06-01"
ServiceFabricMesh:
    tracking: 2018-09-01-preview
ServiceLinker:
    tracking: "2022-05-01"
ServiceNetworking:
    tracking: 2022-10-01-preview
SignalRService:
    tracking: "2022-02-01"
SoftwarePlan:
    tracking: "2019-12-01"
Solutions:
    tracking: "2021-07-01"
Sql:
    tracking: "2021-11-01"
    additions:
        DatabaseThreatDetectionPolicy: "2014-04-01"
        DisasterRecoveryConfiguration: "2014-04-01"
        ServerCommunicationLink: "2014-04-01"
SqlVirtualMachine:
    tracking: "2022-02-01"
StorSimple:
    tracking: "2017-06-01"
Storage:
    tracking: "2022-09-01"
StorageCache:
    tracking: "2022-05-01"
StorageMover:
    tracking: 2022-07-01-preview
StoragePool:
    tracking: "2021-08-01"
StorageSync:
    tracking: "2022-06-01"
StreamAnalytics:
    tracking: 2021-10-01-preview
    additions:
        Cluster: "2020-03-01"
        PrivateEndpoint: "2020-03-01"
        listClusterStreamingJobs: "2020-03-01"
Subscription:
    tracking: "2021-10-01"
Support: {}
Synapse:
    tracking: "2021-06-01"
Syntex:
    tracking: 2022-09-15-preview
TestBase:
    tracking: 2022-04-01-preview
TimeSeriesInsights:
    tracking: 2021-06-30-preview
VMwareCloudSimple:
    tracking: "2019-04-01"
VideoAnalyzer:
    tracking: 2021-11-01-preview
    additions:
        listVideoStreamingToken: 2021-05-01-preview
VideoIndexer:
    tracking: "2022-08-01"
VirtualMachineImages:
    tracking: "2022-02-14"
VisualStudio:
    tracking: 2017-11-01-preview
Web:
    tracking: "2022-03-01"
    additions:
        Connection: "2016-06-01"
        ConnectionGateway: "2016-06-01"
        CustomApi: "2016-06-01"
        WebAppAuthSettingsV2: "2021-02-01"
        WebAppAuthSettingsV2Slot: "2021-02-01"
        listConnectionConsentLinks: "2016-06-01"
        listCustomApiWsdlInterfaces: "2016-06-01"
        listWebAppHybridConnectionKeys: "2018-11-01"
        listWebAppHybridConnectionKeysSlot: "2018-11-01"
WebPubSub:
    tracking: "2021-10-01"
WindowsESU:
    tracking: 2019-09-16-preview
WindowsIoT:
    tracking: "2019-06-01"
WorkloadMonitor: {}
Workloads:
    tracking: 2021-12-01-preview
