name: Prerequisites Artifact Capture
description: Compress and upload prerequisites artifacts for schema and binaries

runs:
  using: "composite"
  steps:
      # We manually compress the artifacts because it saves around 30 seconds per run
      - name: Tar artifacts
        shell: bash

        # Use > to combine lines into single command
        run: >
          tar -zcf bin/artifacts.tar.gz -C bin
          pulumi-resource-azure-native
          pulumi-gen-azure-native
          schema-full.json
          metadata-compact.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts.tar.gz
          path: bin/artifacts.tar.gz
