name: Check worktree clean
description: Fail if there's uncommitted changes in git worktree.

runs:
  using: "composite"
  steps:
      - run: git status
        shell: bash

      - name: Check git status
        id: git-status
        shell: bash
        run: echo "STATUS=$(git status -s)" >> $GITHUB_OUTPUT

      - name: Fail if work-tree not clean
        if: steps.git-status.STATUS != ''
        shell: bash
        run: |
          echo "${{ steps.git-status.STATUS }}"
          git diff | head -20
          exit 1
