// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureNextGen.Insights.V20180301.Inputs
{

    /// <summary>
    /// A logic app receiver.
    /// </summary>
    public sealed class LogicAppReceiverArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The callback url where http request sent to.
        /// </summary>
        [Input("callbackUrl", required: true)]
        public Input<string> CallbackUrl { get; set; } = null!;

        /// <summary>
        /// The name of the logic app receiver. Names must be unique across all receivers within an action group.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The azure resource id of the logic app receiver.
        /// </summary>
        [Input("resourceId", required: true)]
        public Input<string> ResourceId { get; set; } = null!;

        public LogicAppReceiverArgs()
        {
        }
    }
}
