# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GetProviderActionOverviewStatusResult',
    'AwaitableGetProviderActionOverviewStatusResult',
    'get_provider_action_overview_status',
    'get_provider_action_overview_status_output',
]

@pulumi.output_type
class GetProviderActionOverviewStatusResult:
    """
    The get overview status response.
    """
    def __init__(__self__, status_list=None):
        if status_list and not isinstance(status_list, list):
            raise TypeError("Expected argument 'status_list' to be a list")
        pulumi.set(__self__, "status_list", status_list)

    @property
    @pulumi.getter(name="statusList")
    def status_list(self) -> Optional[Sequence['outputs.StatusItemResponse']]:
        """
        List of different status items.
        """
        return pulumi.get(self, "status_list")


class AwaitableGetProviderActionOverviewStatusResult(GetProviderActionOverviewStatusResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetProviderActionOverviewStatusResult(
            status_list=self.status_list)


def get_provider_action_overview_status(type: Optional[str] = None,
                                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetProviderActionOverviewStatusResult:
    """
    Get the resource overview status.
    Azure REST API version: 2024-06-27.


    :param str type: The resource type.
    """
    __args__ = dict()
    __args__['type'] = type
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('azure-native:appcomplianceautomation:getProviderActionOverviewStatus', __args__, opts=opts, typ=GetProviderActionOverviewStatusResult).value

    return AwaitableGetProviderActionOverviewStatusResult(
        status_list=pulumi.get(__ret__, 'status_list'))


@_utilities.lift_output_func(get_provider_action_overview_status)
def get_provider_action_overview_status_output(type: Optional[pulumi.Input[Optional[str]]] = None,
                                               opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetProviderActionOverviewStatusResult]:
    """
    Get the resource overview status.
    Azure REST API version: 2024-06-27.


    :param str type: The resource type.
    """
    ...
