// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azurenative.network.outputs;

import com.pulumi.azurenative.network.outputs.GroupMembersItemResponse;
import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ConfigurationGroupResponse {
    /**
     * @return Network group conditional filter.
     * 
     */
    private @Nullable String conditionalMembership;
    /**
     * @return A description of the network group.
     * 
     */
    private @Nullable String description;
    /**
     * @return A friendly name for the network group.
     * 
     */
    private @Nullable String displayName;
    /**
     * @return Group members of network group.
     * 
     */
    private @Nullable List<GroupMembersItemResponse> groupMembers;
    /**
     * @return Resource ID.
     * 
     */
    private @Nullable String id;
    /**
     * @return Group member type.
     * 
     */
    private @Nullable String memberType;
    /**
     * @return The provisioning state of the scope assignment resource.
     * 
     */
    private String provisioningState;

    private ConfigurationGroupResponse() {}
    /**
     * @return Network group conditional filter.
     * 
     */
    public Optional<String> conditionalMembership() {
        return Optional.ofNullable(this.conditionalMembership);
    }
    /**
     * @return A description of the network group.
     * 
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    /**
     * @return A friendly name for the network group.
     * 
     */
    public Optional<String> displayName() {
        return Optional.ofNullable(this.displayName);
    }
    /**
     * @return Group members of network group.
     * 
     */
    public List<GroupMembersItemResponse> groupMembers() {
        return this.groupMembers == null ? List.of() : this.groupMembers;
    }
    /**
     * @return Resource ID.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    /**
     * @return Group member type.
     * 
     */
    public Optional<String> memberType() {
        return Optional.ofNullable(this.memberType);
    }
    /**
     * @return The provisioning state of the scope assignment resource.
     * 
     */
    public String provisioningState() {
        return this.provisioningState;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ConfigurationGroupResponse defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String conditionalMembership;
        private @Nullable String description;
        private @Nullable String displayName;
        private @Nullable List<GroupMembersItemResponse> groupMembers;
        private @Nullable String id;
        private @Nullable String memberType;
        private String provisioningState;
        public Builder() {}
        public Builder(ConfigurationGroupResponse defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.conditionalMembership = defaults.conditionalMembership;
    	      this.description = defaults.description;
    	      this.displayName = defaults.displayName;
    	      this.groupMembers = defaults.groupMembers;
    	      this.id = defaults.id;
    	      this.memberType = defaults.memberType;
    	      this.provisioningState = defaults.provisioningState;
        }

        @CustomType.Setter
        public Builder conditionalMembership(@Nullable String conditionalMembership) {
            this.conditionalMembership = conditionalMembership;
            return this;
        }
        @CustomType.Setter
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder displayName(@Nullable String displayName) {
            this.displayName = displayName;
            return this;
        }
        @CustomType.Setter
        public Builder groupMembers(@Nullable List<GroupMembersItemResponse> groupMembers) {
            this.groupMembers = groupMembers;
            return this;
        }
        public Builder groupMembers(GroupMembersItemResponse... groupMembers) {
            return groupMembers(List.of(groupMembers));
        }
        @CustomType.Setter
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder memberType(@Nullable String memberType) {
            this.memberType = memberType;
            return this;
        }
        @CustomType.Setter
        public Builder provisioningState(String provisioningState) {
            this.provisioningState = Objects.requireNonNull(provisioningState);
            return this;
        }
        public ConfigurationGroupResponse build() {
            final var o = new ConfigurationGroupResponse();
            o.conditionalMembership = conditionalMembership;
            o.description = description;
            o.displayName = displayName;
            o.groupMembers = groupMembers;
            o.id = id;
            o.memberType = memberType;
            o.provisioningState = provisioningState;
            return o;
        }
    }
}
