// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureNative.Workloads.V20240201Preview.Inputs
{

    /// <summary>
    /// Gets or sets the Oracle provider properties.
    /// </summary>
    public sealed class OracleProviderInstancePropertiesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Gets or sets the oracle database name.
        /// </summary>
        [Input("dbName")]
        public Input<string>? DbName { get; set; }

        /// <summary>
        /// Gets or sets the oracle database password.
        /// </summary>
        [Input("dbPassword")]
        public Input<string>? DbPassword { get; set; }

        /// <summary>
        /// Gets or sets the key vault URI to secret with the database password.
        /// </summary>
        [Input("dbPasswordUri")]
        public Input<string>? DbPasswordUri { get; set; }

        /// <summary>
        /// Gets or sets the oracle database sql port.
        /// </summary>
        [Input("dbPort")]
        public Input<string>? DbPort { get; set; }

        /// <summary>
        /// Gets or sets the oracle database user name.
        /// </summary>
        [Input("dbUsername")]
        public Input<string>? DbUsername { get; set; }

        /// <summary>
        /// Gets or sets the target virtual machine name.
        /// </summary>
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        /// <summary>
        /// The provider type. For example, the value can be SapHana.
        /// Expected value is 'Oracle'.
        /// </summary>
        [Input("providerType", required: true)]
        public Input<string> ProviderType { get; set; } = null!;

        /// <summary>
        /// Gets or sets the SAP System Identifier
        /// </summary>
        [Input("sapSid")]
        public Input<string>? SapSid { get; set; }

        /// <summary>
        /// Gets or sets the blob URI to SSL certificate for the Oracle Database.
        /// </summary>
        [Input("sslCertificateUri")]
        public Input<string>? SslCertificateUri { get; set; }

        /// <summary>
        /// Gets or sets certificate preference if secure communication is enabled.
        /// </summary>
        [Input("sslPreference")]
        public InputUnion<string, Pulumi.AzureNative.Workloads.V20240201Preview.SslPreference>? SslPreference { get; set; }

        public OracleProviderInstancePropertiesArgs()
        {
        }
        public static new OracleProviderInstancePropertiesArgs Empty => new OracleProviderInstancePropertiesArgs();
    }
}
