// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azurenative.elasticsan.outputs;

import com.pulumi.azurenative.elasticsan.outputs.NetworkRuleSetResponse;
import com.pulumi.azurenative.elasticsan.outputs.SystemDataResponse;
import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetVolumeGroupResult {
    /**
     * @return Type of encryption
     * 
     */
    private String encryption;
    /**
     * @return Azure resource identifier.
     * 
     */
    private String id;
    /**
     * @return Azure resource name.
     * 
     */
    private String name;
    /**
     * @return A collection of rules governing the accessibility from specific network locations.
     * 
     */
    private @Nullable NetworkRuleSetResponse networkAcls;
    /**
     * @return Type of storage target
     * 
     */
    private String protocolType;
    /**
     * @return State of the operation on the resource.
     * 
     */
    private String provisioningState;
    /**
     * @return Resource metadata required by ARM RPC
     * 
     */
    private SystemDataResponse systemData;
    /**
     * @return Azure resource tags.
     * 
     */
    private @Nullable Map<String,String> tags;
    /**
     * @return Azure resource type.
     * 
     */
    private String type;

    private GetVolumeGroupResult() {}
    /**
     * @return Type of encryption
     * 
     */
    public String encryption() {
        return this.encryption;
    }
    /**
     * @return Azure resource identifier.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Azure resource name.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return A collection of rules governing the accessibility from specific network locations.
     * 
     */
    public Optional<NetworkRuleSetResponse> networkAcls() {
        return Optional.ofNullable(this.networkAcls);
    }
    /**
     * @return Type of storage target
     * 
     */
    public String protocolType() {
        return this.protocolType;
    }
    /**
     * @return State of the operation on the resource.
     * 
     */
    public String provisioningState() {
        return this.provisioningState;
    }
    /**
     * @return Resource metadata required by ARM RPC
     * 
     */
    public SystemDataResponse systemData() {
        return this.systemData;
    }
    /**
     * @return Azure resource tags.
     * 
     */
    public Map<String,String> tags() {
        return this.tags == null ? Map.of() : this.tags;
    }
    /**
     * @return Azure resource type.
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetVolumeGroupResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String encryption;
        private String id;
        private String name;
        private @Nullable NetworkRuleSetResponse networkAcls;
        private String protocolType;
        private String provisioningState;
        private SystemDataResponse systemData;
        private @Nullable Map<String,String> tags;
        private String type;
        public Builder() {}
        public Builder(GetVolumeGroupResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.encryption = defaults.encryption;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.networkAcls = defaults.networkAcls;
    	      this.protocolType = defaults.protocolType;
    	      this.provisioningState = defaults.provisioningState;
    	      this.systemData = defaults.systemData;
    	      this.tags = defaults.tags;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder encryption(String encryption) {
            this.encryption = Objects.requireNonNull(encryption);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        @CustomType.Setter
        public Builder networkAcls(@Nullable NetworkRuleSetResponse networkAcls) {
            this.networkAcls = networkAcls;
            return this;
        }
        @CustomType.Setter
        public Builder protocolType(String protocolType) {
            this.protocolType = Objects.requireNonNull(protocolType);
            return this;
        }
        @CustomType.Setter
        public Builder provisioningState(String provisioningState) {
            this.provisioningState = Objects.requireNonNull(provisioningState);
            return this;
        }
        @CustomType.Setter
        public Builder systemData(SystemDataResponse systemData) {
            this.systemData = Objects.requireNonNull(systemData);
            return this;
        }
        @CustomType.Setter
        public Builder tags(@Nullable Map<String,String> tags) {
            this.tags = tags;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        public GetVolumeGroupResult build() {
            final var o = new GetVolumeGroupResult();
            o.encryption = encryption;
            o.id = id;
            o.name = name;
            o.networkAcls = networkAcls;
            o.protocolType = protocolType;
            o.provisioningState = provisioningState;
            o.systemData = systemData;
            o.tags = tags;
            o.type = type;
            return o;
        }
    }
}
