// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureNative.HybridNetwork.Outputs
{

    /// <summary>
    /// Manifest artifact properties.
    /// </summary>
    [OutputType]
    public sealed class ManifestArtifactFormatResponse
    {
        /// <summary>
        /// The artifact name
        /// </summary>
        public readonly string? ArtifactName;
        /// <summary>
        /// The artifact type.
        /// </summary>
        public readonly string? ArtifactType;
        /// <summary>
        /// The artifact version.
        /// </summary>
        public readonly string? ArtifactVersion;

        [OutputConstructor]
        private ManifestArtifactFormatResponse(
            string? artifactName,

            string? artifactType,

            string? artifactVersion)
        {
            ArtifactName = artifactName;
            ArtifactType = artifactType;
            ArtifactVersion = artifactVersion;
        }
    }
}
