// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureNative.HybridNetwork.V20230901.Outputs
{

    /// <summary>
    /// The AzureOperatorNexusCluster NFVI detail.
    /// </summary>
    [OutputType]
    public sealed class AzureOperatorNexusClusterNFVIDetailsResponse
    {
        /// <summary>
        /// The reference to the custom location.
        /// </summary>
        public readonly Outputs.ReferencedResourceResponse? CustomLocationReference;
        /// <summary>
        /// Name of the nfvi.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// The NFVI type.
        /// Expected value is 'AzureOperatorNexus'.
        /// </summary>
        public readonly string NfviType;

        [OutputConstructor]
        private AzureOperatorNexusClusterNFVIDetailsResponse(
            Outputs.ReferencedResourceResponse? customLocationReference,

            string? name,

            string nfviType)
        {
            CustomLocationReference = customLocationReference;
            Name = name;
            NfviType = nfviType;
        }
    }
}
