name: Install Languages & Frameworks
description: Installs Go, Pulumi, Node.JS Python and optionally dotnet and Java (if not in quick mode)

inputs:
  skip_dotnet_and_java:
    description: Set to "true" to skip dotnet and java
    # These take 13 and 25 seconds, respectively

runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "provider/go.mod"
        cache-dependency-path: |
          provider/go.sum
          examples/go.sum

    - name: Install Pulumi CLI
      uses: pulumi/actions@v6
      with:
        pulumi-version: dev

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Setup DotNet
      if: inputs.skip_dotnet_and_java != 'true'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x

    - name: Setup Java
      if: inputs.skip_dotnet_and_java != 'true'
      uses: actions/setup-java@v4
      with:
        java-version: "11"
        distribution: temurin
        cache: gradle

    - name: Setup Gradle
      if: inputs.skip_dotnet_and_java != 'true'
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: "8.7"
