// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

export * as v20150701 from "./v20150701/input";
export * as v20160901 from "./v20160901/input";
export * as v20170401 from "./v20170401/input";
export * as v20170601preview from "./v20170601preview/input";
export * as v20180101preview from "./v20180101preview/input";
export * as v20180301 from "./v20180301/input";
export * as v20180501 from "./v20180501/input";
export * as v20180501preview from "./v20180501preview/input";
export * as v20190101 from "./v20190101/input";
export * as v20190601 from "./v20190601/input";
export * as v20190901 from "./v20190901/input";
export * as v20200301 from "./v20200301/input";
export * as v20200501 from "./v20200501/input";
export * as v20200701preview from "./v20200701preview/input";
export * as v20200901 from "./v20200901/input";
export * as v20201001 from "./v20201001/input";
export * as v20201001preview from "./v20201001preview/input";
export * as v20210301preview from "./v20210301preview/input";
export * as v20210601 from "./v20210601/input";
export * as v20210701preview from "./v20210701preview/input";
export * as v20211116preview from "./v20211116preview/input";
export * as v20211201preview from "./v20211201preview/input";
export * as v20220401 from "./v20220401/input";
export * as v20220601 from "./v20220601/input";
export * as v20220701preview from "./v20220701preview/input";
export * as v20220801preview from "./v20220801preview/input";
