// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureNative.Compute
{
    public static class GetCapacityReservationGroup
    {
        /// <summary>
        /// The operation that retrieves information about a capacity reservation group.
        /// 
        /// Uses Azure REST API version 2024-11-01.
        /// 
        /// Other available API versions: 2022-08-01, 2022-11-01, 2023-03-01, 2023-07-01, 2023-09-01, 2024-03-01, 2024-07-01, 2025-04-01. These can be accessed by generating a local SDK package using the CLI command `pulumi package add azure-native compute [ApiVersion]`. See the [version guide](../../../version-guide/#accessing-any-api-version-via-local-packages) for details.
        /// </summary>
        public static Task<GetCapacityReservationGroupResult> InvokeAsync(GetCapacityReservationGroupArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCapacityReservationGroupResult>("azure-native:compute:getCapacityReservationGroup", args ?? new GetCapacityReservationGroupArgs(), options.WithDefaults());

        /// <summary>
        /// The operation that retrieves information about a capacity reservation group.
        /// 
        /// Uses Azure REST API version 2024-11-01.
        /// 
        /// Other available API versions: 2022-08-01, 2022-11-01, 2023-03-01, 2023-07-01, 2023-09-01, 2024-03-01, 2024-07-01, 2025-04-01. These can be accessed by generating a local SDK package using the CLI command `pulumi package add azure-native compute [ApiVersion]`. See the [version guide](../../../version-guide/#accessing-any-api-version-via-local-packages) for details.
        /// </summary>
        public static Output<GetCapacityReservationGroupResult> Invoke(GetCapacityReservationGroupInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCapacityReservationGroupResult>("azure-native:compute:getCapacityReservationGroup", args ?? new GetCapacityReservationGroupInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// The operation that retrieves information about a capacity reservation group.
        /// 
        /// Uses Azure REST API version 2024-11-01.
        /// 
        /// Other available API versions: 2022-08-01, 2022-11-01, 2023-03-01, 2023-07-01, 2023-09-01, 2024-03-01, 2024-07-01, 2025-04-01. These can be accessed by generating a local SDK package using the CLI command `pulumi package add azure-native compute [ApiVersion]`. See the [version guide](../../../version-guide/#accessing-any-api-version-via-local-packages) for details.
        /// </summary>
        public static Output<GetCapacityReservationGroupResult> Invoke(GetCapacityReservationGroupInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetCapacityReservationGroupResult>("azure-native:compute:getCapacityReservationGroup", args ?? new GetCapacityReservationGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCapacityReservationGroupArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the capacity reservation group.
        /// </summary>
        [Input("capacityReservationGroupName", required: true)]
        public string CapacityReservationGroupName { get; set; } = null!;

        /// <summary>
        /// The expand expression to apply on the operation. 'InstanceView' will retrieve the list of instance views of the capacity reservations under the capacity reservation group which is a snapshot of the runtime properties of a capacity reservation that is managed by the platform and can change outside of control plane operations.
        /// </summary>
        [Input("expand")]
        public string? Expand { get; set; }

        /// <summary>
        /// The name of the resource group. The name is case insensitive.
        /// </summary>
        [Input("resourceGroupName", required: true)]
        public string ResourceGroupName { get; set; } = null!;

        public GetCapacityReservationGroupArgs()
        {
        }
        public static new GetCapacityReservationGroupArgs Empty => new GetCapacityReservationGroupArgs();
    }

    public sealed class GetCapacityReservationGroupInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the capacity reservation group.
        /// </summary>
        [Input("capacityReservationGroupName", required: true)]
        public Input<string> CapacityReservationGroupName { get; set; } = null!;

        /// <summary>
        /// The expand expression to apply on the operation. 'InstanceView' will retrieve the list of instance views of the capacity reservations under the capacity reservation group which is a snapshot of the runtime properties of a capacity reservation that is managed by the platform and can change outside of control plane operations.
        /// </summary>
        [Input("expand")]
        public Input<string>? Expand { get; set; }

        /// <summary>
        /// The name of the resource group. The name is case insensitive.
        /// </summary>
        [Input("resourceGroupName", required: true)]
        public Input<string> ResourceGroupName { get; set; } = null!;

        public GetCapacityReservationGroupInvokeArgs()
        {
        }
        public static new GetCapacityReservationGroupInvokeArgs Empty => new GetCapacityReservationGroupInvokeArgs();
    }


    [OutputType]
    public sealed class GetCapacityReservationGroupResult
    {
        /// <summary>
        /// The Azure API version of the resource.
        /// </summary>
        public readonly string AzureApiVersion;
        /// <summary>
        /// A list of all capacity reservation resource ids that belong to capacity reservation group.
        /// </summary>
        public readonly ImmutableArray<Outputs.SubResourceReadOnlyResponse> CapacityReservations;
        /// <summary>
        /// Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The capacity reservation group instance view which has the list of instance views for all the capacity reservations that belong to the capacity reservation group.
        /// </summary>
        public readonly Outputs.CapacityReservationGroupInstanceViewResponse InstanceView;
        /// <summary>
        /// The geo-location where the resource lives
        /// </summary>
        public readonly string Location;
        /// <summary>
        /// The name of the resource
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Specifies the settings to enable sharing across subscriptions for the capacity reservation group resource. The capacity reservation group resource can generally be shared across subscriptions belonging to a single Azure AAD tenant or across AAD tenants if there is a trust relationship established between the tenants.  Block capacity reservation does not support sharing across subscriptions. **Note:** Minimum api-version: 2023-09-01. Please refer to https://aka.ms/computereservationsharing for more details.
        /// </summary>
        public readonly Outputs.ResourceSharingProfileResponse? SharingProfile;
        /// <summary>
        /// Azure Resource Manager metadata containing createdBy and modifiedBy information.
        /// </summary>
        public readonly Outputs.SystemDataResponse SystemData;
        /// <summary>
        /// Resource tags.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Tags;
        /// <summary>
        /// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// A list of references to all virtual machines associated to the capacity reservation group.
        /// </summary>
        public readonly ImmutableArray<Outputs.SubResourceReadOnlyResponse> VirtualMachinesAssociated;
        /// <summary>
        /// The availability zones.
        /// </summary>
        public readonly ImmutableArray<string> Zones;

        [OutputConstructor]
        private GetCapacityReservationGroupResult(
            string azureApiVersion,

            ImmutableArray<Outputs.SubResourceReadOnlyResponse> capacityReservations,

            string id,

            Outputs.CapacityReservationGroupInstanceViewResponse instanceView,

            string location,

            string name,

            Outputs.ResourceSharingProfileResponse? sharingProfile,

            Outputs.SystemDataResponse systemData,

            ImmutableDictionary<string, string>? tags,

            string type,

            ImmutableArray<Outputs.SubResourceReadOnlyResponse> virtualMachinesAssociated,

            ImmutableArray<string> zones)
        {
            AzureApiVersion = azureApiVersion;
            CapacityReservations = capacityReservations;
            Id = id;
            InstanceView = instanceView;
            Location = location;
            Name = name;
            SharingProfile = sharingProfile;
            SystemData = systemData;
            Tags = tags;
            Type = type;
            VirtualMachinesAssociated = virtualMachinesAssociated;
            Zones = zones;
        }
    }
}
