// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package v20200101preview

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func ListConnectedClusterUserCredentials(ctx *pulumi.Context, args *ListConnectedClusterUserCredentialsArgs, opts ...pulumi.InvokeOption) (*ListConnectedClusterUserCredentialsResult, error) {
	var rv ListConnectedClusterUserCredentialsResult
	err := ctx.Invoke("azure-native:kubernetes/v20200101preview:listConnectedClusterUserCredentials", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListConnectedClusterUserCredentialsArgs struct {
	AuthenticationMethod string                     `pulumi:"authenticationMethod"`
	ClientProxy          *bool                      `pulumi:"clientProxy"`
	ClusterName          string                     `pulumi:"clusterName"`
	ResourceGroupName    string                     `pulumi:"resourceGroupName"`
	Value                AuthenticationDetailsValue `pulumi:"value"`
}

// The list of credential result response.
type ListConnectedClusterUserCredentialsResult struct {
	HybridConnectionConfig HybridConnectionConfigResponse `pulumi:"hybridConnectionConfig"`
	Kubeconfigs            []CredentialResultResponse     `pulumi:"kubeconfigs"`
}
