// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureRM.Databricks.V20180401.Outputs
{

    [OutputType]
    public sealed class VirtualNetworkPeeringPropertiesFormatResponseResult
    {
        /// <summary>
        /// Whether the forwarded traffic from the VMs in the local virtual network will be allowed/disallowed in remote virtual network.
        /// </summary>
        public readonly bool? AllowForwardedTraffic;
        /// <summary>
        /// If gateway links can be used in remote virtual networking to link to this virtual network.
        /// </summary>
        public readonly bool? AllowGatewayTransit;
        /// <summary>
        /// Whether the VMs in the local virtual network space would be able to access the VMs in remote virtual network space.
        /// </summary>
        public readonly bool? AllowVirtualNetworkAccess;
        /// <summary>
        /// The reference to the databricks virtual network address space.
        /// </summary>
        public readonly Outputs.AddressSpaceResponseResult? DatabricksAddressSpace;
        /// <summary>
        ///  The remote virtual network should be in the same region. See here to learn more (https://docs.microsoft.com/en-us/azure/databricks/administration-guide/cloud-configurations/azure/vnet-peering).
        /// </summary>
        public readonly Outputs.VirtualNetworkPeeringPropertiesFormatResponsePropertiesResult? DatabricksVirtualNetwork;
        /// <summary>
        /// The status of the virtual network peering.
        /// </summary>
        public readonly string PeeringState;
        /// <summary>
        /// The provisioning state of the virtual network peering resource.
        /// </summary>
        public readonly string ProvisioningState;
        /// <summary>
        /// The reference to the remote virtual network address space.
        /// </summary>
        public readonly Outputs.AddressSpaceResponseResult? RemoteAddressSpace;
        /// <summary>
        ///  The remote virtual network should be in the same region. See here to learn more (https://docs.microsoft.com/en-us/azure/databricks/administration-guide/cloud-configurations/azure/vnet-peering).
        /// </summary>
        public readonly Outputs.VirtualNetworkPeeringPropertiesFormatResponsePropertiesResult RemoteVirtualNetwork;
        /// <summary>
        /// If remote gateways can be used on this virtual network. If the flag is set to true, and allowGatewayTransit on remote peering is also true, virtual network will use gateways of remote virtual network for transit. Only one peering can have this flag set to true. This flag cannot be set if virtual network already has a gateway.
        /// </summary>
        public readonly bool? UseRemoteGateways;

        [OutputConstructor]
        private VirtualNetworkPeeringPropertiesFormatResponseResult(
            bool? allowForwardedTraffic,

            bool? allowGatewayTransit,

            bool? allowVirtualNetworkAccess,

            Outputs.AddressSpaceResponseResult? databricksAddressSpace,

            Outputs.VirtualNetworkPeeringPropertiesFormatResponsePropertiesResult? databricksVirtualNetwork,

            string peeringState,

            string provisioningState,

            Outputs.AddressSpaceResponseResult? remoteAddressSpace,

            Outputs.VirtualNetworkPeeringPropertiesFormatResponsePropertiesResult remoteVirtualNetwork,

            bool? useRemoteGateways)
        {
            AllowForwardedTraffic = allowForwardedTraffic;
            AllowGatewayTransit = allowGatewayTransit;
            AllowVirtualNetworkAccess = allowVirtualNetworkAccess;
            DatabricksAddressSpace = databricksAddressSpace;
            DatabricksVirtualNetwork = databricksVirtualNetwork;
            PeeringState = peeringState;
            ProvisioningState = provisioningState;
            RemoteAddressSpace = remoteAddressSpace;
            RemoteVirtualNetwork = remoteVirtualNetwork;
            UseRemoteGateways = useRemoteGateways;
        }
    }
}
