// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { DatabaseAccountArgs } from "./databaseAccount";
export type DatabaseAccount = import("./databaseAccount").DatabaseAccount;
export const DatabaseAccount: typeof import("./databaseAccount").DatabaseAccount = null as any;
utilities.lazyLoad(exports, ["DatabaseAccount"], () => require("./databaseAccount"));

export { DatabaseAccountCassandraKeyspaceArgs } from "./databaseAccountCassandraKeyspace";
export type DatabaseAccountCassandraKeyspace = import("./databaseAccountCassandraKeyspace").DatabaseAccountCassandraKeyspace;
export const DatabaseAccountCassandraKeyspace: typeof import("./databaseAccountCassandraKeyspace").DatabaseAccountCassandraKeyspace = null as any;
utilities.lazyLoad(exports, ["DatabaseAccountCassandraKeyspace"], () => require("./databaseAccountCassandraKeyspace"));

export { DatabaseAccountCassandraTableArgs } from "./databaseAccountCassandraTable";
export type DatabaseAccountCassandraTable = import("./databaseAccountCassandraTable").DatabaseAccountCassandraTable;
export const DatabaseAccountCassandraTable: typeof import("./databaseAccountCassandraTable").DatabaseAccountCassandraTable = null as any;
utilities.lazyLoad(exports, ["DatabaseAccountCassandraTable"], () => require("./databaseAccountCassandraTable"));

export { DatabaseAccountGremlinDatabaseArgs } from "./databaseAccountGremlinDatabase";
export type DatabaseAccountGremlinDatabase = import("./databaseAccountGremlinDatabase").DatabaseAccountGremlinDatabase;
export const DatabaseAccountGremlinDatabase: typeof import("./databaseAccountGremlinDatabase").DatabaseAccountGremlinDatabase = null as any;
utilities.lazyLoad(exports, ["DatabaseAccountGremlinDatabase"], () => require("./databaseAccountGremlinDatabase"));

export { DatabaseAccountGremlinGraphArgs } from "./databaseAccountGremlinGraph";
export type DatabaseAccountGremlinGraph = import("./databaseAccountGremlinGraph").DatabaseAccountGremlinGraph;
export const DatabaseAccountGremlinGraph: typeof import("./databaseAccountGremlinGraph").DatabaseAccountGremlinGraph = null as any;
utilities.lazyLoad(exports, ["DatabaseAccountGremlinGraph"], () => require("./databaseAccountGremlinGraph"));

export { DatabaseAccountMongoDBCollectionArgs } from "./databaseAccountMongoDBCollection";
export type DatabaseAccountMongoDBCollection = import("./databaseAccountMongoDBCollection").DatabaseAccountMongoDBCollection;
export const DatabaseAccountMongoDBCollection: typeof import("./databaseAccountMongoDBCollection").DatabaseAccountMongoDBCollection = null as any;
utilities.lazyLoad(exports, ["DatabaseAccountMongoDBCollection"], () => require("./databaseAccountMongoDBCollection"));

export { DatabaseAccountMongoDBDatabaseArgs } from "./databaseAccountMongoDBDatabase";
export type DatabaseAccountMongoDBDatabase = import("./databaseAccountMongoDBDatabase").DatabaseAccountMongoDBDatabase;
export const DatabaseAccountMongoDBDatabase: typeof import("./databaseAccountMongoDBDatabase").DatabaseAccountMongoDBDatabase = null as any;
utilities.lazyLoad(exports, ["DatabaseAccountMongoDBDatabase"], () => require("./databaseAccountMongoDBDatabase"));

export { DatabaseAccountSqlContainerArgs } from "./databaseAccountSqlContainer";
export type DatabaseAccountSqlContainer = import("./databaseAccountSqlContainer").DatabaseAccountSqlContainer;
export const DatabaseAccountSqlContainer: typeof import("./databaseAccountSqlContainer").DatabaseAccountSqlContainer = null as any;
utilities.lazyLoad(exports, ["DatabaseAccountSqlContainer"], () => require("./databaseAccountSqlContainer"));

export { DatabaseAccountSqlDatabaseArgs } from "./databaseAccountSqlDatabase";
export type DatabaseAccountSqlDatabase = import("./databaseAccountSqlDatabase").DatabaseAccountSqlDatabase;
export const DatabaseAccountSqlDatabase: typeof import("./databaseAccountSqlDatabase").DatabaseAccountSqlDatabase = null as any;
utilities.lazyLoad(exports, ["DatabaseAccountSqlDatabase"], () => require("./databaseAccountSqlDatabase"));

export { DatabaseAccountTableArgs } from "./databaseAccountTable";
export type DatabaseAccountTable = import("./databaseAccountTable").DatabaseAccountTable;
export const DatabaseAccountTable: typeof import("./databaseAccountTable").DatabaseAccountTable = null as any;
utilities.lazyLoad(exports, ["DatabaseAccountTable"], () => require("./databaseAccountTable"));

export { GetDatabaseAccountArgs, GetDatabaseAccountResult, GetDatabaseAccountOutputArgs } from "./getDatabaseAccount";
export const getDatabaseAccount: typeof import("./getDatabaseAccount").getDatabaseAccount = null as any;
export const getDatabaseAccountOutput: typeof import("./getDatabaseAccount").getDatabaseAccountOutput = null as any;
utilities.lazyLoad(exports, ["getDatabaseAccount","getDatabaseAccountOutput"], () => require("./getDatabaseAccount"));

export { GetDatabaseAccountCassandraKeyspaceArgs, GetDatabaseAccountCassandraKeyspaceResult, GetDatabaseAccountCassandraKeyspaceOutputArgs } from "./getDatabaseAccountCassandraKeyspace";
export const getDatabaseAccountCassandraKeyspace: typeof import("./getDatabaseAccountCassandraKeyspace").getDatabaseAccountCassandraKeyspace = null as any;
export const getDatabaseAccountCassandraKeyspaceOutput: typeof import("./getDatabaseAccountCassandraKeyspace").getDatabaseAccountCassandraKeyspaceOutput = null as any;
utilities.lazyLoad(exports, ["getDatabaseAccountCassandraKeyspace","getDatabaseAccountCassandraKeyspaceOutput"], () => require("./getDatabaseAccountCassandraKeyspace"));

export { GetDatabaseAccountCassandraTableArgs, GetDatabaseAccountCassandraTableResult, GetDatabaseAccountCassandraTableOutputArgs } from "./getDatabaseAccountCassandraTable";
export const getDatabaseAccountCassandraTable: typeof import("./getDatabaseAccountCassandraTable").getDatabaseAccountCassandraTable = null as any;
export const getDatabaseAccountCassandraTableOutput: typeof import("./getDatabaseAccountCassandraTable").getDatabaseAccountCassandraTableOutput = null as any;
utilities.lazyLoad(exports, ["getDatabaseAccountCassandraTable","getDatabaseAccountCassandraTableOutput"], () => require("./getDatabaseAccountCassandraTable"));

export { GetDatabaseAccountGremlinDatabaseArgs, GetDatabaseAccountGremlinDatabaseResult, GetDatabaseAccountGremlinDatabaseOutputArgs } from "./getDatabaseAccountGremlinDatabase";
export const getDatabaseAccountGremlinDatabase: typeof import("./getDatabaseAccountGremlinDatabase").getDatabaseAccountGremlinDatabase = null as any;
export const getDatabaseAccountGremlinDatabaseOutput: typeof import("./getDatabaseAccountGremlinDatabase").getDatabaseAccountGremlinDatabaseOutput = null as any;
utilities.lazyLoad(exports, ["getDatabaseAccountGremlinDatabase","getDatabaseAccountGremlinDatabaseOutput"], () => require("./getDatabaseAccountGremlinDatabase"));

export { GetDatabaseAccountGremlinGraphArgs, GetDatabaseAccountGremlinGraphResult, GetDatabaseAccountGremlinGraphOutputArgs } from "./getDatabaseAccountGremlinGraph";
export const getDatabaseAccountGremlinGraph: typeof import("./getDatabaseAccountGremlinGraph").getDatabaseAccountGremlinGraph = null as any;
export const getDatabaseAccountGremlinGraphOutput: typeof import("./getDatabaseAccountGremlinGraph").getDatabaseAccountGremlinGraphOutput = null as any;
utilities.lazyLoad(exports, ["getDatabaseAccountGremlinGraph","getDatabaseAccountGremlinGraphOutput"], () => require("./getDatabaseAccountGremlinGraph"));

export { GetDatabaseAccountMongoDBCollectionArgs, GetDatabaseAccountMongoDBCollectionResult, GetDatabaseAccountMongoDBCollectionOutputArgs } from "./getDatabaseAccountMongoDBCollection";
export const getDatabaseAccountMongoDBCollection: typeof import("./getDatabaseAccountMongoDBCollection").getDatabaseAccountMongoDBCollection = null as any;
export const getDatabaseAccountMongoDBCollectionOutput: typeof import("./getDatabaseAccountMongoDBCollection").getDatabaseAccountMongoDBCollectionOutput = null as any;
utilities.lazyLoad(exports, ["getDatabaseAccountMongoDBCollection","getDatabaseAccountMongoDBCollectionOutput"], () => require("./getDatabaseAccountMongoDBCollection"));

export { GetDatabaseAccountMongoDBDatabaseArgs, GetDatabaseAccountMongoDBDatabaseResult, GetDatabaseAccountMongoDBDatabaseOutputArgs } from "./getDatabaseAccountMongoDBDatabase";
export const getDatabaseAccountMongoDBDatabase: typeof import("./getDatabaseAccountMongoDBDatabase").getDatabaseAccountMongoDBDatabase = null as any;
export const getDatabaseAccountMongoDBDatabaseOutput: typeof import("./getDatabaseAccountMongoDBDatabase").getDatabaseAccountMongoDBDatabaseOutput = null as any;
utilities.lazyLoad(exports, ["getDatabaseAccountMongoDBDatabase","getDatabaseAccountMongoDBDatabaseOutput"], () => require("./getDatabaseAccountMongoDBDatabase"));

export { GetDatabaseAccountSqlContainerArgs, GetDatabaseAccountSqlContainerResult, GetDatabaseAccountSqlContainerOutputArgs } from "./getDatabaseAccountSqlContainer";
export const getDatabaseAccountSqlContainer: typeof import("./getDatabaseAccountSqlContainer").getDatabaseAccountSqlContainer = null as any;
export const getDatabaseAccountSqlContainerOutput: typeof import("./getDatabaseAccountSqlContainer").getDatabaseAccountSqlContainerOutput = null as any;
utilities.lazyLoad(exports, ["getDatabaseAccountSqlContainer","getDatabaseAccountSqlContainerOutput"], () => require("./getDatabaseAccountSqlContainer"));

export { GetDatabaseAccountSqlDatabaseArgs, GetDatabaseAccountSqlDatabaseResult, GetDatabaseAccountSqlDatabaseOutputArgs } from "./getDatabaseAccountSqlDatabase";
export const getDatabaseAccountSqlDatabase: typeof import("./getDatabaseAccountSqlDatabase").getDatabaseAccountSqlDatabase = null as any;
export const getDatabaseAccountSqlDatabaseOutput: typeof import("./getDatabaseAccountSqlDatabase").getDatabaseAccountSqlDatabaseOutput = null as any;
utilities.lazyLoad(exports, ["getDatabaseAccountSqlDatabase","getDatabaseAccountSqlDatabaseOutput"], () => require("./getDatabaseAccountSqlDatabase"));

export { GetDatabaseAccountTableArgs, GetDatabaseAccountTableResult, GetDatabaseAccountTableOutputArgs } from "./getDatabaseAccountTable";
export const getDatabaseAccountTable: typeof import("./getDatabaseAccountTable").getDatabaseAccountTable = null as any;
export const getDatabaseAccountTableOutput: typeof import("./getDatabaseAccountTable").getDatabaseAccountTableOutput = null as any;
utilities.lazyLoad(exports, ["getDatabaseAccountTable","getDatabaseAccountTableOutput"], () => require("./getDatabaseAccountTable"));

export { ListDatabaseAccountConnectionStringsArgs, ListDatabaseAccountConnectionStringsResult, ListDatabaseAccountConnectionStringsOutputArgs } from "./listDatabaseAccountConnectionStrings";
export const listDatabaseAccountConnectionStrings: typeof import("./listDatabaseAccountConnectionStrings").listDatabaseAccountConnectionStrings = null as any;
export const listDatabaseAccountConnectionStringsOutput: typeof import("./listDatabaseAccountConnectionStrings").listDatabaseAccountConnectionStringsOutput = null as any;
utilities.lazyLoad(exports, ["listDatabaseAccountConnectionStrings","listDatabaseAccountConnectionStringsOutput"], () => require("./listDatabaseAccountConnectionStrings"));

export { ListDatabaseAccountKeysArgs, ListDatabaseAccountKeysResult, ListDatabaseAccountKeysOutputArgs } from "./listDatabaseAccountKeys";
export const listDatabaseAccountKeys: typeof import("./listDatabaseAccountKeys").listDatabaseAccountKeys = null as any;
export const listDatabaseAccountKeysOutput: typeof import("./listDatabaseAccountKeys").listDatabaseAccountKeysOutput = null as any;
utilities.lazyLoad(exports, ["listDatabaseAccountKeys","listDatabaseAccountKeysOutput"], () => require("./listDatabaseAccountKeys"));


// Export enums:
export * from "../../types/enums/documentdb/v20160319";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "azure-native:documentdb/v20160319:DatabaseAccount":
                return new DatabaseAccount(name, <any>undefined, { urn })
            case "azure-native:documentdb/v20160319:DatabaseAccountCassandraKeyspace":
                return new DatabaseAccountCassandraKeyspace(name, <any>undefined, { urn })
            case "azure-native:documentdb/v20160319:DatabaseAccountCassandraTable":
                return new DatabaseAccountCassandraTable(name, <any>undefined, { urn })
            case "azure-native:documentdb/v20160319:DatabaseAccountGremlinDatabase":
                return new DatabaseAccountGremlinDatabase(name, <any>undefined, { urn })
            case "azure-native:documentdb/v20160319:DatabaseAccountGremlinGraph":
                return new DatabaseAccountGremlinGraph(name, <any>undefined, { urn })
            case "azure-native:documentdb/v20160319:DatabaseAccountMongoDBCollection":
                return new DatabaseAccountMongoDBCollection(name, <any>undefined, { urn })
            case "azure-native:documentdb/v20160319:DatabaseAccountMongoDBDatabase":
                return new DatabaseAccountMongoDBDatabase(name, <any>undefined, { urn })
            case "azure-native:documentdb/v20160319:DatabaseAccountSqlContainer":
                return new DatabaseAccountSqlContainer(name, <any>undefined, { urn })
            case "azure-native:documentdb/v20160319:DatabaseAccountSqlDatabase":
                return new DatabaseAccountSqlDatabase(name, <any>undefined, { urn })
            case "azure-native:documentdb/v20160319:DatabaseAccountTable":
                return new DatabaseAccountTable(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("azure-native", "documentdb/v20160319", _module)
