// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureNative.ContainerService.V20210201.Outputs
{

    /// <summary>
    /// The time span with start and end properties.
    /// </summary>
    [OutputType]
    public sealed class TimeSpanResponse
    {
        /// <summary>
        /// The end of a time span
        /// </summary>
        public readonly string? End;
        /// <summary>
        /// The start of a time span
        /// </summary>
        public readonly string? Start;

        [OutputConstructor]
        private TimeSpanResponse(
            string? end,

            string? start)
        {
            End = end;
            Start = start;
        }
    }
}
