// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureRM.Media.Inputs
{

    /// <summary>
    /// Properties of the Media Services account.
    /// </summary>
    public sealed class MediaServicePropertiesResponseArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The account encryption properties.
        /// </summary>
        [Input("encryption")]
        public Input<Inputs.AccountEncryptionResponseArgs>? Encryption { get; set; }

        /// <summary>
        /// The Media Services account ID.
        /// </summary>
        [Input("mediaServiceId", required: true)]
        public Input<string> MediaServiceId { get; set; } = null!;

        [Input("storageAccounts")]
        private InputList<Inputs.StorageAccountResponseArgs>? _storageAccounts;

        /// <summary>
        /// The storage accounts for this resource.
        /// </summary>
        public InputList<Inputs.StorageAccountResponseArgs> StorageAccounts
        {
            get => _storageAccounts ?? (_storageAccounts = new InputList<Inputs.StorageAccountResponseArgs>());
            set => _storageAccounts = value;
        }

        [Input("storageAuthentication")]
        public Input<string>? StorageAuthentication { get; set; }

        public MediaServicePropertiesResponseArgs()
        {
        }
    }
}
