// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package storsimple

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

// The storage account credential.
type ManagerStorageAccountCredential struct {
	pulumi.CustomResourceState

	// The Kind of the object. Currently only Series8000 is supported
	Kind pulumi.StringPtrOutput `pulumi:"kind"`
	// The name of the object.
	Name pulumi.StringOutput `pulumi:"name"`
	// The storage account credential properties.
	Properties StorageAccountCredentialPropertiesResponseOutput `pulumi:"properties"`
	// The hierarchical type of the object.
	Type pulumi.StringOutput `pulumi:"type"`
}

// NewManagerStorageAccountCredential registers a new resource with the given unique name, arguments, and options.
func NewManagerStorageAccountCredential(ctx *pulumi.Context,
	name string, args *ManagerStorageAccountCredentialArgs, opts ...pulumi.ResourceOption) (*ManagerStorageAccountCredential, error) {
	if args == nil || args.ManagerName == nil {
		return nil, errors.New("missing required argument 'ManagerName'")
	}
	if args == nil || args.Name == nil {
		return nil, errors.New("missing required argument 'Name'")
	}
	if args == nil || args.Properties == nil {
		return nil, errors.New("missing required argument 'Properties'")
	}
	if args == nil || args.ResourceGroupName == nil {
		return nil, errors.New("missing required argument 'ResourceGroupName'")
	}
	if args == nil {
		args = &ManagerStorageAccountCredentialArgs{}
	}
	var resource ManagerStorageAccountCredential
	err := ctx.RegisterResource("azurerm:storsimple:ManagerStorageAccountCredential", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetManagerStorageAccountCredential gets an existing ManagerStorageAccountCredential resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetManagerStorageAccountCredential(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ManagerStorageAccountCredentialState, opts ...pulumi.ResourceOption) (*ManagerStorageAccountCredential, error) {
	var resource ManagerStorageAccountCredential
	err := ctx.ReadResource("azurerm:storsimple:ManagerStorageAccountCredential", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ManagerStorageAccountCredential resources.
type managerStorageAccountCredentialState struct {
	// The Kind of the object. Currently only Series8000 is supported
	Kind *string `pulumi:"kind"`
	// The name of the object.
	Name *string `pulumi:"name"`
	// The storage account credential properties.
	Properties *StorageAccountCredentialPropertiesResponse `pulumi:"properties"`
	// The hierarchical type of the object.
	Type *string `pulumi:"type"`
}

type ManagerStorageAccountCredentialState struct {
	// The Kind of the object. Currently only Series8000 is supported
	Kind pulumi.StringPtrInput
	// The name of the object.
	Name pulumi.StringPtrInput
	// The storage account credential properties.
	Properties StorageAccountCredentialPropertiesResponsePtrInput
	// The hierarchical type of the object.
	Type pulumi.StringPtrInput
}

func (ManagerStorageAccountCredentialState) ElementType() reflect.Type {
	return reflect.TypeOf((*managerStorageAccountCredentialState)(nil)).Elem()
}

type managerStorageAccountCredentialArgs struct {
	// The Kind of the object. Currently only Series8000 is supported
	Kind *string `pulumi:"kind"`
	// The manager name
	ManagerName string `pulumi:"managerName"`
	// The storage account credential name.
	Name string `pulumi:"name"`
	// The storage account credential properties.
	Properties StorageAccountCredentialProperties `pulumi:"properties"`
	// The resource group name
	ResourceGroupName string `pulumi:"resourceGroupName"`
}

// The set of arguments for constructing a ManagerStorageAccountCredential resource.
type ManagerStorageAccountCredentialArgs struct {
	// The Kind of the object. Currently only Series8000 is supported
	Kind pulumi.StringPtrInput
	// The manager name
	ManagerName pulumi.StringInput
	// The storage account credential name.
	Name pulumi.StringInput
	// The storage account credential properties.
	Properties StorageAccountCredentialPropertiesInput
	// The resource group name
	ResourceGroupName pulumi.StringInput
}

func (ManagerStorageAccountCredentialArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*managerStorageAccountCredentialArgs)(nil)).Elem()
}
