# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'DestinationType',
    'EmissionType',
    'IngestionType',
    'SourceType',
]


class DestinationType(str, Enum):
    AZURE_MONITOR = "AzureMonitor"


class EmissionType(str, Enum):
    IPFIX = "IPFIX"


class IngestionType(str, Enum):
    IPFIX = "IPFIX"


class SourceType(str, Enum):
    RESOURCE = "Resource"
