// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureNative.DataShare.V20200901.Outputs
{

    /// <summary>
    /// Properties of the SQL DW table data set mapping.
    /// </summary>
    [OutputType]
    public sealed class SqlDWTableDataSetMappingPropertiesResponse
    {
        /// <summary>
        /// The id of the source data set.
        /// </summary>
        public readonly string DataSetId;
        /// <summary>
        /// Gets the status of the data set mapping.
        /// </summary>
        public readonly string DataSetMappingStatus;
        /// <summary>
        /// DataWarehouse name of the source data set
        /// </summary>
        public readonly string DataWarehouseName;
        /// <summary>
        /// Provisioning state of the data set mapping.
        /// </summary>
        public readonly string ProvisioningState;
        /// <summary>
        /// Schema of the table. Default value is dbo.
        /// </summary>
        public readonly string SchemaName;
        /// <summary>
        /// Resource id of SQL server
        /// </summary>
        public readonly string SqlServerResourceId;
        /// <summary>
        /// SQL DW table name.
        /// </summary>
        public readonly string TableName;

        [OutputConstructor]
        private SqlDWTableDataSetMappingPropertiesResponse(
            string dataSetId,

            string dataSetMappingStatus,

            string dataWarehouseName,

            string provisioningState,

            string schemaName,

            string sqlServerResourceId,

            string tableName)
        {
            DataSetId = dataSetId;
            DataSetMappingStatus = dataSetMappingStatus;
            DataWarehouseName = dataWarehouseName;
            ProvisioningState = provisioningState;
            SchemaName = schemaName;
            SqlServerResourceId = sqlServerResourceId;
            TableName = tableName;
        }
    }
}
