// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azurenative.portal.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class TerminalSettingsResponse {
    /**
     * @return Size of terminal font.
     * 
     */
    private @Nullable String fontSize;
    /**
     * @return Style of terminal font.
     * 
     */
    private @Nullable String fontStyle;

    private TerminalSettingsResponse() {}
    /**
     * @return Size of terminal font.
     * 
     */
    public Optional<String> fontSize() {
        return Optional.ofNullable(this.fontSize);
    }
    /**
     * @return Style of terminal font.
     * 
     */
    public Optional<String> fontStyle() {
        return Optional.ofNullable(this.fontStyle);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(TerminalSettingsResponse defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String fontSize;
        private @Nullable String fontStyle;
        public Builder() {}
        public Builder(TerminalSettingsResponse defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.fontSize = defaults.fontSize;
    	      this.fontStyle = defaults.fontStyle;
        }

        @CustomType.Setter
        public Builder fontSize(@Nullable String fontSize) {
            this.fontSize = fontSize;
            return this;
        }
        @CustomType.Setter
        public Builder fontStyle(@Nullable String fontStyle) {
            this.fontStyle = fontStyle;
            return this;
        }
        public TerminalSettingsResponse build() {
            final var o = new TerminalSettingsResponse();
            o.fontSize = fontSize;
            o.fontStyle = fontStyle;
            return o;
        }
    }
}
