name: arm2pulumi Release
"on":
  push:
    tags:
      - v*.*.*
      - '!v*.*.*-**'
  workflow_dispatch:
    inputs:
      version:
        description: The version of the binary to deploy - do not include the pulumi prefix in the name.
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow clone
        run: git fetch --prune --unshallow
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.1.0
        with:
          repo: pulumi/pulumictl
      - name: Install Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'
      - name: Set Version if Parameter available
        if: github.event.inputs.version != ''
        run: echo "GORELEASER_CURRENT_TAG=v${{ github.event.inputs.message }}" >> $GITHUB_ENV
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: -p 1 -f .goreleaser.arm2pulumi.yml release --rm-dist --timeout 60m0s
        env:
          GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
