name: arm2pulumi-release
on:
  push:
    tags:
    - v*.*.*
    - "!v*.*.*-**"
  workflow_dispatch:
    inputs:
      version:
        description: The version of the binary to deploy - do not include the pulumi
          prefix in the name.
        required: true
        type: string
env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
  PROVIDER: azure-native
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  TRAVIS_OS_NAME: linux
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
  ARM_CLIENT_ID: 30e520fa-12b4-4e21-b473-9426c5ac2e1e
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_ENVIRONMENT: public
  ARM_LOCATION: westus2
  ARM_SUBSCRIPTION_ID: 0282681f-7a9e-424b-80b2-96babd57a8a1
  ARM_TENANT_ID: 706143bc-e1d4-4593-aee2-c9dc60ab9be7
  GO111MODULE: on
  PULUMI_API: https://api.pulumi-staging.io
jobs:
  release:
    runs-on: macos-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags
    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@v1.5.0
      with:
        repo: pulumi/pulumictl
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.x
    - name: Set Version if Parameter available
      if: github.event.inputs.version != ''
      run: echo "GORELEASER_CURRENT_TAG=v${{ github.event.inputs.message }}" >>
        $GITHUB_ENV
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        args: -p 1 -f .goreleaser.arm2pulumi.yml release --rm-dist --timeout 60m0s
        version: latest
    name: release
