name: arm2pulumi-release

on:
  push:
    tags:
      - v*.*.*
      - "!v*.*.*-**"
  workflow_dispatch:
    inputs:
      version:
        description:
          The version of the binary to deploy - do not include the pulumi
          prefix in the name, but do include the leading "v".
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
  PUBLISH_REPO_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  PUBLISH_REPO_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  PULUMI_API: https://api.pulumi-staging.io
  GORELEASER_CURRENT_TAG: ${{ github.event.inputs.version || ref_name }}

jobs:
  release:
    runs-on: macos-11
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Languages & Frameworks
        uses: ./.github/actions/install
        with:
          skip_dotnet_and_java: "true"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: -p 1 -f .goreleaser.arm2pulumi.yml release --rm-dist --timeout 60m0s
          version: latest
    name: release
