name: azcore-scheduled

on:
  schedule:
    - cron: 15 3 * * 1-6
  workflow_dispatch: {}
  push:
    branches:
      - tkappler/azcore-scheduled

env:
  PULUMI_USE_AUTOREST: "false"

jobs:
  version:
    uses: ./.github/workflows/version.yml
    secrets: inherit

  build_test:
    uses: ./.github/workflows/build-test.yml
    secrets: inherit
    needs: version
    with:
      ref: ${{ github.ref }}
      version: ${{ needs.version.outputs.version }}
      short_test: false
      retention_days: 7
      # We don't specify oidc_arm_client_id, it will default to its correct value.
