name: command-dispatch

on:
  issue_comment:
    types:
      - created
      - edited

env:
  PULUMI_API: https://api.pulumi-staging.io

jobs:
  command-dispatch-for-testing:
    runs-on: ubuntu-latest
    name: command-dispatch-for-testing
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - env:
          ESC_ACTION_ENVIRONMENT: github-secrets/${{ github.repository_owner }}-${{ github.event.repository.name }}
          ESC_ACTION_OIDC_AUTH: "true"
          ESC_ACTION_OIDC_ORGANIZATION: pulumi
          ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
        id: esc-secrets
        name: Fetch secrets from ESC
        uses: pulumi/esc-action@9eb774255b1a4afb7855678ae8d4a77359da0d9b
      - uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: run-acceptance-tests
          permission: write
          issue-type: pull-request
          repository: pulumi/pulumi-azure-native
    if: ${{ github.event.issue.pull_request }}
