name: dev-version

on:
  workflow_call:
    outputs:
      version:
        description: Calculated version
        value: ${{ jobs.version.outputs.version }}


jobs:
  version:
    runs-on: pulumi-ubuntu-8core
    name: Calculate Dev Version
    steps:
      - id: version
        name: Calculate build version
        uses: pulumi/provider-version-action@c4f719182e607d0d8322f148f168d3372838e681 # v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
